/* cgtest_create.c - see cgtest_create.h.
 *
 * "dir" is always a directory, never a file path - cgtest-config.json
 * and cgtest.h are always written as "dir/cgtest-config.json" and
 * "dir/cgtest.h". "dir" is resolved to an absolute path the same way
 * cgtest_config_load() does (getcwd() + cpath_join()), created if it
 * doesn't exist yet (mkdir() - "dir"'s own parent must already exist;
 * this does not create intermediate directories), then the two
 * templates are written inside it.
 */
#include "cgtest_create.h"
#include "cpath.h"
#include "cmsg.h"

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#ifdef _WIN32
#include <direct.h>
#define CGTEST_GETCWD _getcwd
#define CGTEST_MKDIR(path) _mkdir(path)
#else
#include <unistd.h>
#define CGTEST_GETCWD getcwd
#define CGTEST_MKDIR(path) mkdir(path, 0755)
#endif

/* MSVC's <sys/stat.h> defines S_IFDIR/S_IFMT but not the S_ISDIR()
 * convenience macro POSIX builds already get for free. */
#ifndef S_ISDIR
#define S_ISDIR(mode) (((mode) & S_IFMT) == S_IFDIR)
#endif

#define CGTEST_CREATE_PATH_SCRATCH 4096
#define CGTEST_CREATE_ERROR_BUFSZ  256

static const char *const CGTEST_CONFIG_TEMPLATE =
    "{\n"
    "    \"compiler_command\": \"gcc -std=c99 -O3\",\n"
    "    \"msvc\": false,\n"
    "    \"include_paths\": [\n"
    "        \"./include\",\n"
    "        \"./third_party\",\n"
    "        \"/usr/local/include\"\n"
    "    ],\n"
    "    \"source_files\": [\n"
    "        \"./src/foo.c\",\n"
    "        \"./src/bar.c\",\n"
    "        \"./src/baz.c\"\n"
    "    ],\n"
    "    \"output_path\": \"./build\",\n"
    "    \"test_directories\": [\n"
    "        \"./tests\",\n"
    "        \"./unittests\",\n"
    "        \"/home/user/project/tests\"\n"
    "    ]\n"
    "}\n";

/* Split into several literals rather than one: ISO C90 compilers are
 * only required to support string literals up to 509 chars (after
 * adjacent concatenation), and the combined template exceeds that. */
static const char *const CGTEST_H_TEMPLATE_HEAD1 =
    "#ifndef CGTEST_H\n"
    "#define CGTEST_H\n"
    "\n"
    "/* Generated by \"cgtest --create\". Test functions have the form\n"
    " * \"void test_<name>(void) { ... }\" - a plain \"void\" keeps test\n"
    " * files C89-portable (no <stdbool.h>). EXPECT_* macros report a\n"
    " * failed check and keep running the test; ASSERT_* macros report\n"
    " * it and return immediately - use ASSERT for a precondition the\n"
    " * rest of the function depends on (e.g. a NULL check before a\n"
    " * dereference), EXPECT otherwise.\n";

static const char *const CGTEST_H_TEMPLATE_HEAD1B =
    " * The EXPECT_EQ_/EXPECT_NE_ macros (INT/UINT/FLOAT/DOUBLE/PTR/\n"
    " * STR/STR_NOCASE, and their ASSERT_ counterparts) additionally\n"
    " * print both operands' values on failure. FLOAT/DOUBLE compare\n"
    " * via a small relative tolerance rather than exact equality,\n"
    " * appropriate for results of floating-point arithmetic.\n"
    " * EXPECT_NEAR_DOUBLE/ASSERT_NEAR_DOUBLE(expected, actual,\n"
    " * abs_error) instead take a caller-supplied tolerance, for when\n"
    " * the built-in one isn't the right fit. */\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_HEAD2 =
    "#include <ctype.h>\n"
    "#include <float.h>\n"
    "#include <stdio.h>\n"
    "#include <string.h>\n"
    "\n"
    "#ifdef _WIN32\n"
    "#include <direct.h>\n"
    "#define CGTEST_GETCWD _getcwd\n"
    "#else\n"
    "#include <unistd.h>\n"
    "#define CGTEST_GETCWD getcwd\n"
    "#endif\n"
    "\n"
    "/* The generated runner reads this after calling each test to\n"
    " * decide pass/fail, resetting it to 0 first. */\n"
    "extern int cgtest_failed;\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_RELPATH1 =
    "/* Shortens __FILE__ to a path relative to the current working\n"
    " * directory (falls back to the full path if it isn't under it),\n"
    " * so FAIL messages stay short - jump-to-file in an editor's\n"
    " * quickfix list still works as long as the editor's own cwd\n"
    " * matches wherever the test binary was run from. */\n"
    "static const char *cgtest_relpath(const char *file)\n"
    "{\n"
    "    static char cwd[4096];\n"
    "    size_t i;\n"
    "    size_t len;\n"
    "\n"
    "    if (CGTEST_GETCWD(cwd, sizeof(cwd)) == NULL) {\n"
    "        return file;\n"
    "    }\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_RELPATH2 =
    "    len = strlen(cwd);\n"
    "    for (i = 0; i < len; i++) {\n"
    "        char a = file[i];\n"
    "        char b = cwd[i];\n"
    "        if (a == '\\\\') a = '/';\n"
    "        if (b == '\\\\') b = '/';\n"
    "        if (a != b) {\n"
    "            return file;\n"
    "        }\n"
    "    }\n"
    "    if (file[len] != '/' && file[len] != '\\\\') {\n"
    "        return file;\n"
    "    }\n"
    "    return file + len + 1;\n"
    "}\n"
    "\n";

/* Prints one "  <prefix>\"...\"\n" line per '\n' found in "s" - used by
 * EXPECT_EQ_STR/ASSERT_EQ_STR so a real newline embedded in a tested
 * string can't visually merge with the FAIL block around it. Every
 * other non-printable byte - "\r", "\t", other named C escapes, and
 * anything outside 0x20-0x7e (including ESC, which could otherwise
 * inject an arbitrary terminal escape sequence) - is hex-escaped
 * inline instead of passed through raw; none of those are printed as
 * a real control byte, so unlike "\n" none of them need their own
 * line break either. Lines after the first are indented to line up
 * under the opening quote. */
static const char *const CGTEST_H_TEMPLATE_STRFIELD1 =
    "static void cgtest_print_str_field(const char *prefix, const char *s)\n"
    "{\n"
    "    size_t indent = strlen(prefix);\n"
    "    int first = 1;\n"
    "    size_t i;\n"
    "    unsigned char c;\n"
    "\n"
    "    for (;;) {\n"
    "        if (first) {\n"
    "            fprintf(stderr, \"%s\\\"\", prefix);\n"
    "            first = 0;\n"
    "        } else {\n"
    "            for (i = 0; i < indent; i++) {\n"
    "                fputc(' ', stderr);\n"
    "            }\n"
    "            fputc('\"', stderr);\n"
    "        }\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_STRFIELD2 =
    "        for (;;) {\n"
    "            c = (unsigned char)*s;\n"
    "            if (c == '\\0') {\n"
    "                fputs(\"\\\"\\n\", stderr);\n"
    "                return;\n"
    "            }\n"
    "            if (c == '\\n') {\n"
    "                fputs(\"\\\\n\\\"\\n\", stderr);\n"
    "                s++;\n"
    "                break;\n"
    "            }\n"
    "            switch (c) {\n"
    "                case '\\r': fputs(\"\\\\r\", stderr); break;\n"
    "                case '\\t': fputs(\"\\\\t\", stderr); break;\n";

static const char *const CGTEST_H_TEMPLATE_STRFIELD3 =
    "                case '\\a': fputs(\"\\\\a\", stderr); break;\n"
    "                case '\\b': fputs(\"\\\\b\", stderr); break;\n"
    "                case '\\v': fputs(\"\\\\v\", stderr); break;\n"
    "                case '\\f': fputs(\"\\\\f\", stderr); break;\n";

static const char *const CGTEST_H_TEMPLATE_STRFIELD4 =
    "                default:\n"
    "                    if (c < 0x20 || c >= 0x7f) {\n"
    "                        fprintf(stderr, \"\\\\x%02x\", (unsigned int)c);\n"
    "                    } else {\n"
    "                        fputc((int)c, stderr);\n"
    "                    }\n"
    "                    break;\n"
    "            }\n"
    "            s++;\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EXPECT_TRUE =
    "#define EXPECT_TRUE(cond) \\\n"
    "    do { \\\n"
    "        if (!(cond)) { \\\n"
    "            fprintf(stderr, \"%s:%d: FAIL: EXPECT_TRUE(%s)\\n\", cgtest_relpath(__FILE__), __LINE__, #cond); \\\n"
    "            cgtest_failed = 1; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EXPECT_FALSE =
    "#define EXPECT_FALSE(cond) \\\n"
    "    do { \\\n"
    "        if (cond) { \\\n"
    "            fprintf(stderr, \"%s:%d: FAIL: EXPECT_FALSE(%s)\\n\", cgtest_relpath(__FILE__), __LINE__, #cond); \\\n"
    "            cgtest_failed = 1; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_ASSERT_TRUE =
    "#define ASSERT_TRUE(cond) \\\n"
    "    do { \\\n"
    "        if (!(cond)) { \\\n"
    "            fprintf(stderr, \"%s:%d: FAIL: ASSERT_TRUE(%s)\\n\", cgtest_relpath(__FILE__), __LINE__, #cond); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            return; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_ASSERT_FALSE =
    "#define ASSERT_FALSE(cond) \\\n"
    "    do { \\\n"
    "        if (cond) { \\\n"
    "            fprintf(stderr, \"%s:%d: FAIL: ASSERT_FALSE(%s)\\n\", cgtest_relpath(__FILE__), __LINE__, #cond); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            return; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

/* The EXPECT_EQ_/EXPECT_NE_ and ASSERT_ variants below print both
 * operands' values on failure (EXPECT_TRUE/ASSERT_TRUE above only
 * ever show the source text of the whole condition). Each casts both
 * operands to one canonical type per family - long/unsigned long/
 * double/const void pointer - rather than having one macro per exact
 * C type, so e.g. char, short, int and long can all go through
 * EXPECT_EQ_INT. EQ and NE (and EXPECT and ASSERT) share one
 * CGTEST_CMP_*_ comparison core per family, parameterized on the
 * operator that decides failure, the printed label/format, and
 * whether to return afterwards - see EXPECT_EQ_INT/EXPECT_NE_INT
 * below for how it's used. */
static const char *const CGTEST_H_TEMPLATE_CMP_INT1 =
    "#define CGTEST_CMP_INT_(macro_name, fail_op, fmt, on_fail, lhs, rhs) \\\n"
    "    do { \\\n"
    "        long cgtest_lhs_ = (long)(lhs); \\\n"
    "        long cgtest_rhs_ = (long)(rhs); \\\n"
    "        if (cgtest_lhs_ fail_op cgtest_rhs_) { \\\n";

static const char *const CGTEST_H_TEMPLATE_CMP_INT2 =
    "            fprintf(stderr, \"%s:%d: FAIL: \" macro_name \"(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #lhs, #rhs); \\\n"
    "            fprintf(stderr, fmt, cgtest_lhs_, cgtest_rhs_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            on_fail; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EQ_NE_INT =
    "#define EXPECT_EQ_INT(expected, actual) \\\n"
    "    CGTEST_CMP_INT_(\"EXPECT_EQ_INT\", !=, \"  expected: %ld\\n  actual:   %ld\\n\", ((void)0), expected, actual)\n"
    "\n"
    "#define ASSERT_EQ_INT(expected, actual) \\\n"
    "    CGTEST_CMP_INT_(\"ASSERT_EQ_INT\", !=, \"  expected: %ld\\n  actual:   %ld\\n\", return, expected, actual)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EQ_NE_INT2 =
    "#define EXPECT_NE_INT(unexpected, actual) \\\n"
    "    CGTEST_CMP_INT_(\"EXPECT_NE_INT\", ==, \"  unexpected: %ld\\n  actual:     %ld\\n\", ((void)0), unexpected, actual)\n"
    "\n"
    "#define ASSERT_NE_INT(unexpected, actual) \\\n"
    "    CGTEST_CMP_INT_(\"ASSERT_NE_INT\", ==, \"  unexpected: %ld\\n  actual:     %ld\\n\", return, unexpected, actual)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_CMP_UINT1 =
    "#define CGTEST_CMP_UINT_(macro_name, fail_op, fmt, on_fail, lhs, rhs) \\\n"
    "    do { \\\n"
    "        unsigned long cgtest_lhs_ = (unsigned long)(lhs); \\\n"
    "        unsigned long cgtest_rhs_ = (unsigned long)(rhs); \\\n"
    "        if (cgtest_lhs_ fail_op cgtest_rhs_) { \\\n";

static const char *const CGTEST_H_TEMPLATE_CMP_UINT2 =
    "            fprintf(stderr, \"%s:%d: FAIL: \" macro_name \"(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #lhs, #rhs); \\\n"
    "            fprintf(stderr, fmt, cgtest_lhs_, cgtest_rhs_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            on_fail; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EQ_NE_UINT =
    "#define EXPECT_EQ_UINT(expected, actual) \\\n"
    "    CGTEST_CMP_UINT_(\"EXPECT_EQ_UINT\", !=, \"  expected: %lu\\n  actual:   %lu\\n\", ((void)0), expected, actual)\n"
    "\n"
    "#define ASSERT_EQ_UINT(expected, actual) \\\n"
    "    CGTEST_CMP_UINT_(\"ASSERT_EQ_UINT\", !=, \"  expected: %lu\\n  actual:   %lu\\n\", return, expected, actual)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EQ_NE_UINT2 =
    "#define EXPECT_NE_UINT(unexpected, actual) \\\n"
    "    CGTEST_CMP_UINT_(\"EXPECT_NE_UINT\", ==, \"  unexpected: %lu\\n  actual:     %lu\\n\", ((void)0), unexpected, actual)\n"
    "\n"
    "#define ASSERT_NE_UINT(unexpected, actual) \\\n"
    "    CGTEST_CMP_UINT_(\"ASSERT_NE_UINT\", ==, \"  unexpected: %lu\\n  actual:     %lu\\n\", return, unexpected, actual)\n"
    "\n";

/* Approximate equality via a small relative tolerance, replacing
 * exact bitwise equality (which would fail for nearly every real
 * floating-point computation, even ones that are correct for all
 * practical purposes) with something closer in spirit to GoogleTest's
 * ULP-based EXPECT_FLOAT_EQ/EXPECT_DOUBLE_EQ, but using an
 * epsilon-relative diff instead of literal bit-distance - no 64-bit
 * integer type needed for the double case that way, so this stays
 * portable to plain C89. diff = |expected - actual|, scale = max(1.0,
 * |expected|, |actual|) - the 1.0 floor keeps the tolerance from
 * collapsing to near-zero once both values are close to 0 - and
 * tolerance = 4 * EPSILON * scale. No <math.h>/fabs() dependency,
 * same reason cgtest_strcasecmp() avoids strcasecmp(). NE_ is the
 * logical negation (fails when the values ARE within tolerance) -
 * GoogleTest has no "confidently different floats" macro of its own,
 * but every other type family here has a matching NE_, so these do
 * too. CGTEST_APPROX_FLOAT_/CGTEST_APPROX_DOUBLE_ only differ in
 * which C type and <float.h> epsilon constant they use. */
static const char *const CGTEST_H_TEMPLATE_CMP_FLOAT1 =
    "#define CGTEST_APPROX_FLOAT_(macro_name, fail_op, fmt, on_fail, lhs, rhs) \\\n"
    "    do { \\\n"
    "        float cgtest_lhs_ = (float)(lhs); \\\n"
    "        float cgtest_rhs_ = (float)(rhs); \\\n"
    "        float cgtest_diff_raw_ = cgtest_lhs_ - cgtest_rhs_; \\\n";

static const char *const CGTEST_H_TEMPLATE_CMP_FLOAT2 =
    "        float cgtest_diff_ = (cgtest_diff_raw_ < 0 ? -cgtest_diff_raw_ : cgtest_diff_raw_); \\\n"
    "        float cgtest_lhs_abs_ = (cgtest_lhs_ < 0 ? -cgtest_lhs_ : cgtest_lhs_); \\\n"
    "        float cgtest_rhs_abs_ = (cgtest_rhs_ < 0 ? -cgtest_rhs_ : cgtest_rhs_); \\\n";

static const char *const CGTEST_H_TEMPLATE_CMP_FLOAT3 =
    "        float cgtest_scale_ = (cgtest_lhs_abs_ > cgtest_rhs_abs_ ? cgtest_lhs_abs_ : cgtest_rhs_abs_); \\\n"
    "        float cgtest_tol_ = 4 * FLT_EPSILON * (cgtest_scale_ < 1.0f ? 1.0f : cgtest_scale_); \\\n"
    "        if (cgtest_diff_ fail_op cgtest_tol_) { \\\n";

static const char *const CGTEST_H_TEMPLATE_CMP_FLOAT4 =
    "            fprintf(stderr, \"%s:%d: FAIL: \" macro_name \"(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #lhs, #rhs); \\\n"
    "            fprintf(stderr, fmt, cgtest_lhs_, cgtest_rhs_, cgtest_diff_, cgtest_tol_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            on_fail; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EQ_NE_FLOAT =
    "#define EXPECT_EQ_FLOAT(expected, actual) \\\n"
    "    CGTEST_APPROX_FLOAT_(\"EXPECT_EQ_FLOAT\", >, \"  expected: %g\\n  actual:   %g\\n  diff:     %g (max allowed: %g)\\n\", ((void)0), expected, actual)\n"
    "\n"
    "#define ASSERT_EQ_FLOAT(expected, actual) \\\n"
    "    CGTEST_APPROX_FLOAT_(\"ASSERT_EQ_FLOAT\", >, \"  expected: %g\\n  actual:   %g\\n  diff:     %g (max allowed: %g)\\n\", return, expected, actual)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EQ_NE_FLOAT2 =
    "#define EXPECT_NE_FLOAT(unexpected, actual) \\\n"
    "    CGTEST_APPROX_FLOAT_(\"EXPECT_NE_FLOAT\", <=, \"  unexpected: %g\\n  actual:     %g\\n  diff:     %g (must exceed: %g)\\n\", ((void)0), unexpected, actual)\n"
    "\n"
    "#define ASSERT_NE_FLOAT(unexpected, actual) \\\n"
    "    CGTEST_APPROX_FLOAT_(\"ASSERT_NE_FLOAT\", <=, \"  unexpected: %g\\n  actual:     %g\\n  diff:     %g (must exceed: %g)\\n\", return, unexpected, actual)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_CMP_DOUBLE1 =
    "#define CGTEST_APPROX_DOUBLE_(macro_name, fail_op, fmt, on_fail, lhs, rhs) \\\n"
    "    do { \\\n"
    "        double cgtest_lhs_ = (double)(lhs); \\\n"
    "        double cgtest_rhs_ = (double)(rhs); \\\n"
    "        double cgtest_diff_raw_ = cgtest_lhs_ - cgtest_rhs_; \\\n";

static const char *const CGTEST_H_TEMPLATE_CMP_DOUBLE2 =
    "        double cgtest_diff_ = (cgtest_diff_raw_ < 0 ? -cgtest_diff_raw_ : cgtest_diff_raw_); \\\n"
    "        double cgtest_lhs_abs_ = (cgtest_lhs_ < 0 ? -cgtest_lhs_ : cgtest_lhs_); \\\n"
    "        double cgtest_rhs_abs_ = (cgtest_rhs_ < 0 ? -cgtest_rhs_ : cgtest_rhs_); \\\n";

static const char *const CGTEST_H_TEMPLATE_CMP_DOUBLE3 =
    "        double cgtest_scale_ = (cgtest_lhs_abs_ > cgtest_rhs_abs_ ? cgtest_lhs_abs_ : cgtest_rhs_abs_); \\\n"
    "        double cgtest_tol_ = 4 * DBL_EPSILON * (cgtest_scale_ < 1.0 ? 1.0 : cgtest_scale_); \\\n"
    "        if (cgtest_diff_ fail_op cgtest_tol_) { \\\n";

static const char *const CGTEST_H_TEMPLATE_CMP_DOUBLE4 =
    "            fprintf(stderr, \"%s:%d: FAIL: \" macro_name \"(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #lhs, #rhs); \\\n"
    "            fprintf(stderr, fmt, cgtest_lhs_, cgtest_rhs_, cgtest_diff_, cgtest_tol_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            on_fail; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EQ_NE_DOUBLE =
    "#define EXPECT_EQ_DOUBLE(expected, actual) \\\n"
    "    CGTEST_APPROX_DOUBLE_(\"EXPECT_EQ_DOUBLE\", >, \"  expected: %g\\n  actual:   %g\\n  diff:     %g (max allowed: %g)\\n\", ((void)0), expected, actual)\n"
    "\n"
    "#define ASSERT_EQ_DOUBLE(expected, actual) \\\n"
    "    CGTEST_APPROX_DOUBLE_(\"ASSERT_EQ_DOUBLE\", >, \"  expected: %g\\n  actual:   %g\\n  diff:     %g (max allowed: %g)\\n\", return, expected, actual)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EQ_NE_DOUBLE2 =
    "#define EXPECT_NE_DOUBLE(unexpected, actual) \\\n"
    "    CGTEST_APPROX_DOUBLE_(\"EXPECT_NE_DOUBLE\", <=, \"  unexpected: %g\\n  actual:     %g\\n  diff:     %g (must exceed: %g)\\n\", ((void)0), unexpected, actual)\n"
    "\n"
    "#define ASSERT_NE_DOUBLE(unexpected, actual) \\\n"
    "    CGTEST_APPROX_DOUBLE_(\"ASSERT_NE_DOUBLE\", <=, \"  unexpected: %g\\n  actual:     %g\\n  diff:     %g (must exceed: %g)\\n\", return, unexpected, actual)\n"
    "\n";

/* Unlike EXPECT_EQ_DOUBLE's own built-in tolerance, this one takes a
 * caller-supplied abs_error instead - useful when the fixed 4*EPSILON
 * relative tolerance above isn't the right fit (e.g. a much looser or
 * tighter bound than "4 epsilons" is actually appropriate for the
 * computation in question). No <math.h>/fabs() dependency - the sign
 * flip below is all that's needed for an absolute value. */
static const char *const CGTEST_H_TEMPLATE_NEAR_DOUBLE1 =
    "#define CGTEST_NEAR_DOUBLE_(macro_name, on_fail, expected, actual, abs_error) \\\n"
    "    do { \\\n"
    "        double cgtest_exp_ = (double)(expected); \\\n"
    "        double cgtest_act_ = (double)(actual); \\\n"
    "        double cgtest_tol_ = (double)(abs_error); \\\n"
    "        double cgtest_diff_ = cgtest_exp_ - cgtest_act_; \\\n"
    "        if (cgtest_diff_ < 0) { \\\n"
    "            cgtest_diff_ = -cgtest_diff_; \\\n"
    "        } \\\n"
    "        if (cgtest_diff_ > cgtest_tol_) { \\\n";

static const char *const CGTEST_H_TEMPLATE_NEAR_DOUBLE2 =
    "            fprintf(stderr, \"%s:%d: FAIL: \" macro_name \"(%s, %s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual, #abs_error); \\\n"
    "            fprintf(stderr, \"  expected: %g\\n  actual:   %g\\n  diff:     %g (max allowed: %g)\\n\", \\\n"
    "                    cgtest_exp_, cgtest_act_, cgtest_diff_, cgtest_tol_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            on_fail; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_NEAR_DOUBLE3 =
    "#define EXPECT_NEAR_DOUBLE(expected, actual, abs_error) \\\n"
    "    CGTEST_NEAR_DOUBLE_(\"EXPECT_NEAR_DOUBLE\", ((void)0), expected, actual, abs_error)\n"
    "\n"
    "#define ASSERT_NEAR_DOUBLE(expected, actual, abs_error) \\\n"
    "    CGTEST_NEAR_DOUBLE_(\"ASSERT_NEAR_DOUBLE\", return, expected, actual, abs_error)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_CMP_PTR1 =
    "#define CGTEST_CMP_PTR_(macro_name, fail_op, fmt, on_fail, lhs, rhs) \\\n"
    "    do { \\\n"
    "        const void *cgtest_lhs_ = (const void *)(lhs); \\\n"
    "        const void *cgtest_rhs_ = (const void *)(rhs); \\\n"
    "        if (cgtest_lhs_ fail_op cgtest_rhs_) { \\\n";

static const char *const CGTEST_H_TEMPLATE_CMP_PTR2 =
    "            fprintf(stderr, \"%s:%d: FAIL: \" macro_name \"(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #lhs, #rhs); \\\n"
    "            fprintf(stderr, fmt, cgtest_lhs_, cgtest_rhs_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            on_fail; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EQ_NE_PTR =
    "#define EXPECT_EQ_PTR(expected, actual) \\\n"
    "    CGTEST_CMP_PTR_(\"EXPECT_EQ_PTR\", !=, \"  expected: %p\\n  actual:   %p\\n\", ((void)0), expected, actual)\n"
    "\n"
    "#define ASSERT_EQ_PTR(expected, actual) \\\n"
    "    CGTEST_CMP_PTR_(\"ASSERT_EQ_PTR\", !=, \"  expected: %p\\n  actual:   %p\\n\", return, expected, actual)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EQ_NE_PTR2 =
    "#define EXPECT_NE_PTR(unexpected, actual) \\\n"
    "    CGTEST_CMP_PTR_(\"EXPECT_NE_PTR\", ==, \"  unexpected: %p\\n  actual:     %p\\n\", ((void)0), unexpected, actual)\n"
    "\n"
    "#define ASSERT_NE_PTR(unexpected, actual) \\\n"
    "    CGTEST_CMP_PTR_(\"ASSERT_NE_PTR\", ==, \"  unexpected: %p\\n  actual:     %p\\n\", return, unexpected, actual)\n"
    "\n";

/* Content comparison via strcmp(), not pointer equality - two equal
 * C-strings stored at different addresses must still count as equal.
 * Same reason GoogleTest has EXPECT_STREQ separate from EXPECT_EQ.
 * "fail_op" compares strcmp()'s result against 0 (!= for EQ, == for
 * NE), same trick as the CGTEST_CMP_INT_/UINT_/DOUBLE_/PTR_ families
 * above. */
static const char *const CGTEST_H_TEMPLATE_CMP_STR1 =
    "#define CGTEST_CMP_STR_(macro_name, fail_op, lhs_label, rhs_label, on_fail, lhs, rhs) \\\n"
    "    do { \\\n"
    "        const char *cgtest_lhs_ = (lhs); \\\n"
    "        const char *cgtest_rhs_ = (rhs); \\\n"
    "        if (strcmp(cgtest_lhs_, cgtest_rhs_) fail_op 0) { \\\n";

static const char *const CGTEST_H_TEMPLATE_CMP_STR2 =
    "            fprintf(stderr, \"%s:%d: FAIL: \" macro_name \"(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #lhs, #rhs); \\\n"
    "            cgtest_print_str_field(lhs_label, cgtest_lhs_); \\\n"
    "            cgtest_print_str_field(rhs_label, cgtest_rhs_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            on_fail; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EQ_NE_STR =
    "#define EXPECT_EQ_STR(expected, actual) \\\n"
    "    CGTEST_CMP_STR_(\"EXPECT_EQ_STR\", !=, \"  expected: \", \"  actual:   \", ((void)0), expected, actual)\n"
    "\n"
    "#define ASSERT_EQ_STR(expected, actual) \\\n"
    "    CGTEST_CMP_STR_(\"ASSERT_EQ_STR\", !=, \"  expected: \", \"  actual:   \", return, expected, actual)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EQ_NE_STR2 =
    "#define EXPECT_NE_STR(unexpected, actual) \\\n"
    "    CGTEST_CMP_STR_(\"EXPECT_NE_STR\", ==, \"  unexpected: \", \"  actual:     \", ((void)0), unexpected, actual)\n"
    "\n"
    "#define ASSERT_NE_STR(unexpected, actual) \\\n"
    "    CGTEST_CMP_STR_(\"ASSERT_NE_STR\", ==, \"  unexpected: \", \"  actual:     \", return, unexpected, actual)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_STRCASECMP1 =
    "/* Byte-wise case-insensitive comparison, like strcasecmp() - not\n"
    " * used directly since strcasecmp() isn't standard C (POSIX only,\n"
    " * and named _stricmp on MSVC); this stays portable to plain\n"
    " * C89/C99. Returns 0 on a case-insensitive match, same\n"
    " * convention as strcmp(). */\n"
    "static int cgtest_strcasecmp(const char *a, const char *b)\n"
    "{\n"
    "    unsigned char ca, cb;\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_STRCASECMP2 =
    "    for (;;) {\n"
    "        ca = (unsigned char)*a;\n"
    "        cb = (unsigned char)*b;\n"
    "        if (tolower(ca) != tolower(cb)) {\n"
    "            return 1;\n"
    "        }\n"
    "        if (ca == '\\0') {\n"
    "            return 0;\n"
    "        }\n"
    "        a++;\n"
    "        b++;\n"
    "    }\n"
    "}\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_CMP_STR_NOCASE1 =
    "#define CGTEST_CMP_STR_NOCASE_(macro_name, fail_op, lhs_label, rhs_label, on_fail, lhs, rhs) \\\n"
    "    do { \\\n"
    "        const char *cgtest_lhs_ = (lhs); \\\n"
    "        const char *cgtest_rhs_ = (rhs); \\\n"
    "        if (cgtest_strcasecmp(cgtest_lhs_, cgtest_rhs_) fail_op 0) { \\\n";

static const char *const CGTEST_H_TEMPLATE_CMP_STR_NOCASE2 =
    "            fprintf(stderr, \"%s:%d: FAIL: \" macro_name \"(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #lhs, #rhs); \\\n"
    "            cgtest_print_str_field(lhs_label, cgtest_lhs_); \\\n"
    "            cgtest_print_str_field(rhs_label, cgtest_rhs_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            on_fail; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EQ_NE_STR_NOCASE =
    "#define EXPECT_EQ_STR_NOCASE(expected, actual) \\\n"
    "    CGTEST_CMP_STR_NOCASE_(\"EXPECT_EQ_STR_NOCASE\", !=, \"  expected: \", \"  actual:   \", ((void)0), expected, actual)\n"
    "\n"
    "#define ASSERT_EQ_STR_NOCASE(expected, actual) \\\n"
    "    CGTEST_CMP_STR_NOCASE_(\"ASSERT_EQ_STR_NOCASE\", !=, \"  expected: \", \"  actual:   \", return, expected, actual)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EQ_NE_STR_NOCASE2 =
    "#define EXPECT_NE_STR_NOCASE(unexpected, actual) \\\n"
    "    CGTEST_CMP_STR_NOCASE_(\"EXPECT_NE_STR_NOCASE\", ==, \"  unexpected: \", \"  actual:     \", ((void)0), unexpected, actual)\n"
    "\n"
    "#define ASSERT_NE_STR_NOCASE(unexpected, actual) \\\n"
    "    CGTEST_CMP_STR_NOCASE_(\"ASSERT_NE_STR_NOCASE\", ==, \"  unexpected: \", \"  actual:     \", return, unexpected, actual)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_FOOTER =
    "#endif /* CGTEST_H */\n";

static CGTestCreateResult cgtest_create_fail(const char *message)
{
    CGTestCreateResult result;
    result.ok = 0;
    result.error = cmsg_dup(message, strlen(message));
    return result;
}

/* The variadic "..." parts (each a "const char *", terminated by a
 * NULL sentinel) are written back to back into one file - lets a
 * template be split across as many string literals as needed (see
 * CGTEST_H_TEMPLATE_HEAD1 and friends) without ever concatenating
 * them in memory. */
static int cgtest_create_write_file(const char *path, char *error_buf, size_t error_buf_size, ...)
{
    FILE *f;
    va_list args;
    const char *part;
    size_t len;

    f = fopen(path, "wb");
    if (f == NULL) {
        cmsg_build(error_buf, error_buf_size, "could not create ", path, strlen(path), "");
        return 0;
    }

    va_start(args, error_buf_size);
    for (part = va_arg(args, const char *); part != NULL; part = va_arg(args, const char *)) {
        len = strlen(part);
        if (fwrite(part, 1, len, f) != len) {
            va_end(args);
            fclose(f);
            cmsg_build(error_buf, error_buf_size, "could not write ", path, strlen(path), "");
            return 0;
        }
    }
    va_end(args);

    fclose(f);
    return 1;
}

CGTestCreateResult cgtest_create_run(const char *dir)
{
    CGTestCreateResult result;
    char cwd[CGTEST_CREATE_PATH_SCRATCH];
    char abs_dir_scratch[CGTEST_CREATE_PATH_SCRATCH];
    char config_scratch[CGTEST_CREATE_PATH_SCRATCH];
    char header_scratch[CGTEST_CREATE_PATH_SCRATCH];
    CPath abs_dir;
    CPath config_path;
    CPath header_path;
    struct stat st;
    char error_buf[CGTEST_CREATE_ERROR_BUFSZ];

    if (CGTEST_GETCWD(cwd, sizeof(cwd)) == NULL) {
        return cgtest_create_fail("could not determine the current working directory");
    }

    abs_dir = cpath_join(abs_dir_scratch, sizeof(abs_dir_scratch), cwd, dir);

    if (stat(abs_dir.data, &st) != 0) {
        if (CGTEST_MKDIR(abs_dir.data) != 0) {
            cmsg_build(error_buf, sizeof(error_buf), "could not create directory ", abs_dir.data, abs_dir.length, "");
            return cgtest_create_fail(error_buf);
        }
    } else if (!S_ISDIR(st.st_mode)) {
        cmsg_build(error_buf, sizeof(error_buf), "not a directory: ", abs_dir.data, abs_dir.length, "");
        return cgtest_create_fail(error_buf);
    }

    config_path = cpath_join(config_scratch, sizeof(config_scratch), abs_dir.data, "cgtest-config.json");

    if (stat(config_path.data, &st) == 0) {
        cmsg_build(error_buf, sizeof(error_buf), "cgtest-config.json already exists: ",
                   config_path.data, config_path.length, "");
        return cgtest_create_fail(error_buf);
    }

    header_path = cpath_join(header_scratch, sizeof(header_scratch), abs_dir.data, "cgtest.h");

    if (!cgtest_create_write_file(config_path.data, error_buf, sizeof(error_buf),
                                   CGTEST_CONFIG_TEMPLATE, (const char *)NULL)) {
        return cgtest_create_fail(error_buf);
    }
    if (!cgtest_create_write_file(header_path.data, error_buf, sizeof(error_buf),
                                   CGTEST_H_TEMPLATE_HEAD1, CGTEST_H_TEMPLATE_HEAD1B, CGTEST_H_TEMPLATE_HEAD2,
                                   CGTEST_H_TEMPLATE_RELPATH1, CGTEST_H_TEMPLATE_RELPATH2,
                                   CGTEST_H_TEMPLATE_STRFIELD1, CGTEST_H_TEMPLATE_STRFIELD2,
                                   CGTEST_H_TEMPLATE_STRFIELD3, CGTEST_H_TEMPLATE_STRFIELD4,
                                   CGTEST_H_TEMPLATE_EXPECT_TRUE, CGTEST_H_TEMPLATE_EXPECT_FALSE,
                                   CGTEST_H_TEMPLATE_ASSERT_TRUE, CGTEST_H_TEMPLATE_ASSERT_FALSE,
                                   CGTEST_H_TEMPLATE_CMP_INT1, CGTEST_H_TEMPLATE_CMP_INT2,
                                   CGTEST_H_TEMPLATE_EQ_NE_INT, CGTEST_H_TEMPLATE_EQ_NE_INT2,
                                   CGTEST_H_TEMPLATE_CMP_UINT1, CGTEST_H_TEMPLATE_CMP_UINT2,
                                   CGTEST_H_TEMPLATE_EQ_NE_UINT, CGTEST_H_TEMPLATE_EQ_NE_UINT2,
                                   CGTEST_H_TEMPLATE_CMP_FLOAT1, CGTEST_H_TEMPLATE_CMP_FLOAT2,
                                   CGTEST_H_TEMPLATE_CMP_FLOAT3, CGTEST_H_TEMPLATE_CMP_FLOAT4,
                                   CGTEST_H_TEMPLATE_EQ_NE_FLOAT, CGTEST_H_TEMPLATE_EQ_NE_FLOAT2,
                                   CGTEST_H_TEMPLATE_CMP_DOUBLE1, CGTEST_H_TEMPLATE_CMP_DOUBLE2,
                                   CGTEST_H_TEMPLATE_CMP_DOUBLE3, CGTEST_H_TEMPLATE_CMP_DOUBLE4,
                                   CGTEST_H_TEMPLATE_EQ_NE_DOUBLE, CGTEST_H_TEMPLATE_EQ_NE_DOUBLE2,
                                   CGTEST_H_TEMPLATE_NEAR_DOUBLE1, CGTEST_H_TEMPLATE_NEAR_DOUBLE2,
                                   CGTEST_H_TEMPLATE_NEAR_DOUBLE3,
                                   CGTEST_H_TEMPLATE_CMP_PTR1, CGTEST_H_TEMPLATE_CMP_PTR2,
                                   CGTEST_H_TEMPLATE_EQ_NE_PTR, CGTEST_H_TEMPLATE_EQ_NE_PTR2,
                                   CGTEST_H_TEMPLATE_STRCASECMP1, CGTEST_H_TEMPLATE_STRCASECMP2,
                                   CGTEST_H_TEMPLATE_CMP_STR1, CGTEST_H_TEMPLATE_CMP_STR2,
                                   CGTEST_H_TEMPLATE_EQ_NE_STR, CGTEST_H_TEMPLATE_EQ_NE_STR2,
                                   CGTEST_H_TEMPLATE_CMP_STR_NOCASE1, CGTEST_H_TEMPLATE_CMP_STR_NOCASE2,
                                   CGTEST_H_TEMPLATE_EQ_NE_STR_NOCASE, CGTEST_H_TEMPLATE_EQ_NE_STR_NOCASE2,
                                   CGTEST_H_TEMPLATE_FOOTER,
                                   (const char *)NULL)) {
        return cgtest_create_fail(error_buf);
    }

    result.ok = 1;
    result.error = NULL;
    return result;
}

void cgtest_create_free(CGTestCreateResult *result)
{
    free(result->error);
    result->error = NULL;
}
