/* cgtest_create.c - see cgtest_create.h.
 *
 * "dir" is always a directory, never a file path - cgtest-config.json
 * and cgtest.h are always written as "dir/cgtest-config.json" and
 * "dir/cgtest.h". "dir" is resolved to an absolute path the same way
 * cgtest_config_load() does (getcwd() + cpath_join()), created if it
 * doesn't exist yet (mkdir() - "dir"'s own parent must already exist;
 * this does not create intermediate directories), then the two
 * templates are written inside it.
 */
#include "cgtest_create.h"
#include "cpath.h"
#include "cmsg.h"

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#ifdef _WIN32
#include <direct.h>
#define CGTEST_GETCWD _getcwd
#define CGTEST_MKDIR(path) _mkdir(path)
#else
#include <unistd.h>
#define CGTEST_GETCWD getcwd
#define CGTEST_MKDIR(path) mkdir(path, 0755)
#endif

#define CGTEST_CREATE_PATH_SCRATCH 4096
#define CGTEST_CREATE_ERROR_BUFSZ  256

static const char *const CGTEST_CONFIG_TEMPLATE =
    "{\n"
    "    \"compiler_command\": \"gcc -std=c99 -O3\",\n"
    "    \"include_paths\": [\n"
    "        \"./include\",\n"
    "        \"./third_party\",\n"
    "        \"/usr/local/include\"\n"
    "    ],\n"
    "    \"source_files\": [\n"
    "        \"./src/foo.c\",\n"
    "        \"./src/bar.c\",\n"
    "        \"./src/baz.c\"\n"
    "    ],\n"
    "    \"output_path\": \"./build\",\n"
    "    \"test_directories\": [\n"
    "        \"./tests\",\n"
    "        \"./unittests\",\n"
    "        \"/home/user/project/tests\"\n"
    "    ]\n"
    "}\n";

/* Split into several literals rather than one: ISO C90 compilers are
 * only required to support string literals up to 509 chars (after
 * adjacent concatenation), and the combined template exceeds that. */
static const char *const CGTEST_H_TEMPLATE_HEAD1 =
    "#ifndef CGTEST_H\n"
    "#define CGTEST_H\n"
    "\n"
    "/* Generated by \"cgtest --create\". Test functions have the form\n"
    " * \"void test_<name>(void) { ... }\" - a plain \"void\" keeps test\n"
    " * files C89-portable (no <stdbool.h>). EXPECT_* macros report a\n"
    " * failed check and keep running the test; ASSERT_* macros report\n"
    " * it and return immediately - use ASSERT for a precondition the\n"
    " * rest of the function depends on (e.g. a NULL check before a\n"
    " * dereference), EXPECT otherwise.\n";

static const char *const CGTEST_H_TEMPLATE_HEAD1B =
    " * The EXPECT_EQ_INT/UINT/DOUBLE/PTR/STR macros (and their\n"
    " * ASSERT_EQ_ counterparts) additionally print both operands'\n"
    " * values on failure. */\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_HEAD2 =
    "#include <stdio.h>\n"
    "#include <string.h>\n"
    "\n"
    "#ifdef _WIN32\n"
    "#include <direct.h>\n"
    "#define CGTEST_GETCWD _getcwd\n"
    "#else\n"
    "#include <unistd.h>\n"
    "#define CGTEST_GETCWD getcwd\n"
    "#endif\n"
    "\n"
    "/* The generated runner reads this after calling each test to\n"
    " * decide pass/fail, resetting it to 0 first. */\n"
    "extern int cgtest_failed;\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_RELPATH1 =
    "/* Shortens __FILE__ to a path relative to the current working\n"
    " * directory (falls back to the full path if it isn't under it),\n"
    " * so FAIL messages stay short - jump-to-file in an editor's\n"
    " * quickfix list still works as long as the editor's own cwd\n"
    " * matches wherever the test binary was run from. */\n"
    "static const char *cgtest_relpath(const char *file)\n"
    "{\n"
    "    static char cwd[4096];\n"
    "    size_t i;\n"
    "    size_t len;\n"
    "\n"
    "    if (CGTEST_GETCWD(cwd, sizeof(cwd)) == NULL) {\n"
    "        return file;\n"
    "    }\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_RELPATH2 =
    "    len = strlen(cwd);\n"
    "    for (i = 0; i < len; i++) {\n"
    "        char a = file[i];\n"
    "        char b = cwd[i];\n"
    "        if (a == '\\\\') a = '/';\n"
    "        if (b == '\\\\') b = '/';\n"
    "        if (a != b) {\n"
    "            return file;\n"
    "        }\n"
    "    }\n"
    "    if (file[len] != '/' && file[len] != '\\\\') {\n"
    "        return file;\n"
    "    }\n"
    "    return file + len + 1;\n"
    "}\n"
    "\n";

/* Prints one "  <prefix>\"...\"\n" line per '\n' found in "s" - used by
 * EXPECT_EQ_STR/ASSERT_EQ_STR so a real newline embedded in a tested
 * string can't visually merge with the FAIL block around it. Every
 * other non-printable byte - "\r", "\t", other named C escapes, and
 * anything outside 0x20-0x7e (including ESC, which could otherwise
 * inject an arbitrary terminal escape sequence) - is hex-escaped
 * inline instead of passed through raw; none of those are printed as
 * a real control byte, so unlike "\n" none of them need their own
 * line break either. Lines after the first are indented to line up
 * under the opening quote. */
static const char *const CGTEST_H_TEMPLATE_STRFIELD1 =
    "static void cgtest_print_str_field(const char *prefix, const char *s)\n"
    "{\n"
    "    size_t indent = strlen(prefix);\n"
    "    int first = 1;\n"
    "    size_t i;\n"
    "    unsigned char c;\n"
    "\n"
    "    for (;;) {\n"
    "        if (first) {\n"
    "            fprintf(stderr, \"%s\\\"\", prefix);\n"
    "            first = 0;\n"
    "        } else {\n"
    "            for (i = 0; i < indent; i++) {\n"
    "                fputc(' ', stderr);\n"
    "            }\n"
    "            fputc('\"', stderr);\n"
    "        }\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_STRFIELD2 =
    "        for (;;) {\n"
    "            c = (unsigned char)*s;\n"
    "            if (c == '\\0') {\n"
    "                fputs(\"\\\"\\n\", stderr);\n"
    "                return;\n"
    "            }\n"
    "            if (c == '\\n') {\n"
    "                fputs(\"\\\\n\\\"\\n\", stderr);\n"
    "                s++;\n"
    "                break;\n"
    "            }\n"
    "            switch (c) {\n"
    "                case '\\r': fputs(\"\\\\r\", stderr); break;\n"
    "                case '\\t': fputs(\"\\\\t\", stderr); break;\n";

static const char *const CGTEST_H_TEMPLATE_STRFIELD3 =
    "                case '\\a': fputs(\"\\\\a\", stderr); break;\n"
    "                case '\\b': fputs(\"\\\\b\", stderr); break;\n"
    "                case '\\v': fputs(\"\\\\v\", stderr); break;\n"
    "                case '\\f': fputs(\"\\\\f\", stderr); break;\n";

static const char *const CGTEST_H_TEMPLATE_STRFIELD4 =
    "                default:\n"
    "                    if (c < 0x20 || c >= 0x7f) {\n"
    "                        fprintf(stderr, \"\\\\x%02x\", (unsigned int)c);\n"
    "                    } else {\n"
    "                        fputc((int)c, stderr);\n"
    "                    }\n"
    "                    break;\n"
    "            }\n"
    "            s++;\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EXPECT_TRUE =
    "#define EXPECT_TRUE(cond) \\\n"
    "    do { \\\n"
    "        if (!(cond)) { \\\n"
    "            fprintf(stderr, \"%s:%d: FAIL: EXPECT_TRUE(%s)\\n\", cgtest_relpath(__FILE__), __LINE__, #cond); \\\n"
    "            cgtest_failed = 1; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EXPECT_FALSE =
    "#define EXPECT_FALSE(cond) \\\n"
    "    do { \\\n"
    "        if (cond) { \\\n"
    "            fprintf(stderr, \"%s:%d: FAIL: EXPECT_FALSE(%s)\\n\", cgtest_relpath(__FILE__), __LINE__, #cond); \\\n"
    "            cgtest_failed = 1; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_ASSERT_TRUE =
    "#define ASSERT_TRUE(cond) \\\n"
    "    do { \\\n"
    "        if (!(cond)) { \\\n"
    "            fprintf(stderr, \"%s:%d: FAIL: ASSERT_TRUE(%s)\\n\", cgtest_relpath(__FILE__), __LINE__, #cond); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            return; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_ASSERT_FALSE =
    "#define ASSERT_FALSE(cond) \\\n"
    "    do { \\\n"
    "        if (cond) { \\\n"
    "            fprintf(stderr, \"%s:%d: FAIL: ASSERT_FALSE(%s)\\n\", cgtest_relpath(__FILE__), __LINE__, #cond); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            return; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

/* The EXPECT_EQ_ and ASSERT_EQ_ variants below print both operands'
 * values on failure (EXPECT_TRUE/ASSERT_TRUE above only ever show
 * the source text of the whole condition). Each casts both operands
 * to one canonical type per family - long/unsigned long/double/
 * const void pointer - rather than having one macro per exact C
 * type, so e.g. char, short, int and long can all go through
 * EXPECT_EQ_INT. */
static const char *const CGTEST_H_TEMPLATE_EXPECT_EQ_INT =
    "#define EXPECT_EQ_INT(expected, actual) \\\n"
    "    do { \\\n"
    "        long cgtest_exp_ = (long)(expected); \\\n"
    "        long cgtest_act_ = (long)(actual); \\\n"
    "        if (cgtest_exp_ != cgtest_act_) { \\\n";

static const char *const CGTEST_H_TEMPLATE_EXPECT_EQ_INT2 =
    "            fprintf(stderr, \"%s:%d: FAIL: EXPECT_EQ_INT(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \\\n"
    "            fprintf(stderr, \"  expected: %ld\\n  actual:   %ld\\n\", cgtest_exp_, cgtest_act_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_ASSERT_EQ_INT =
    "#define ASSERT_EQ_INT(expected, actual) \\\n"
    "    do { \\\n"
    "        long cgtest_exp_ = (long)(expected); \\\n"
    "        long cgtest_act_ = (long)(actual); \\\n"
    "        if (cgtest_exp_ != cgtest_act_) { \\\n";

static const char *const CGTEST_H_TEMPLATE_ASSERT_EQ_INT2 =
    "            fprintf(stderr, \"%s:%d: FAIL: ASSERT_EQ_INT(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \\\n"
    "            fprintf(stderr, \"  expected: %ld\\n  actual:   %ld\\n\", cgtest_exp_, cgtest_act_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            return; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EXPECT_EQ_UINT =
    "#define EXPECT_EQ_UINT(expected, actual) \\\n"
    "    do { \\\n"
    "        unsigned long cgtest_exp_ = (unsigned long)(expected); \\\n"
    "        unsigned long cgtest_act_ = (unsigned long)(actual); \\\n"
    "        if (cgtest_exp_ != cgtest_act_) { \\\n";

static const char *const CGTEST_H_TEMPLATE_EXPECT_EQ_UINT2 =
    "            fprintf(stderr, \"%s:%d: FAIL: EXPECT_EQ_UINT(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \\\n"
    "            fprintf(stderr, \"  expected: %lu\\n  actual:   %lu\\n\", cgtest_exp_, cgtest_act_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_ASSERT_EQ_UINT =
    "#define ASSERT_EQ_UINT(expected, actual) \\\n"
    "    do { \\\n"
    "        unsigned long cgtest_exp_ = (unsigned long)(expected); \\\n"
    "        unsigned long cgtest_act_ = (unsigned long)(actual); \\\n"
    "        if (cgtest_exp_ != cgtest_act_) { \\\n";

static const char *const CGTEST_H_TEMPLATE_ASSERT_EQ_UINT2 =
    "            fprintf(stderr, \"%s:%d: FAIL: ASSERT_EQ_UINT(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \\\n"
    "            fprintf(stderr, \"  expected: %lu\\n  actual:   %lu\\n\", cgtest_exp_, cgtest_act_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            return; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

/* Exact equality, like EXPECT_EQ_INT - no ULP-based tolerance the
 * way GoogleTest's EXPECT_DOUBLE_EQ has, so this is only reliable
 * for values that were never computed (e.g. a literal echoed back
 * unchanged), not results of arithmetic that could differ by a
 * rounding error. */
static const char *const CGTEST_H_TEMPLATE_EXPECT_EQ_DOUBLE =
    "#define EXPECT_EQ_DOUBLE(expected, actual) \\\n"
    "    do { \\\n"
    "        double cgtest_exp_ = (double)(expected); \\\n"
    "        double cgtest_act_ = (double)(actual); \\\n"
    "        if (cgtest_exp_ != cgtest_act_) { \\\n";

static const char *const CGTEST_H_TEMPLATE_EXPECT_EQ_DOUBLE2 =
    "            fprintf(stderr, \"%s:%d: FAIL: EXPECT_EQ_DOUBLE(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \\\n"
    "            fprintf(stderr, \"  expected: %g\\n  actual:   %g\\n\", cgtest_exp_, cgtest_act_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_ASSERT_EQ_DOUBLE =
    "#define ASSERT_EQ_DOUBLE(expected, actual) \\\n"
    "    do { \\\n"
    "        double cgtest_exp_ = (double)(expected); \\\n"
    "        double cgtest_act_ = (double)(actual); \\\n"
    "        if (cgtest_exp_ != cgtest_act_) { \\\n";

static const char *const CGTEST_H_TEMPLATE_ASSERT_EQ_DOUBLE2 =
    "            fprintf(stderr, \"%s:%d: FAIL: ASSERT_EQ_DOUBLE(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \\\n"
    "            fprintf(stderr, \"  expected: %g\\n  actual:   %g\\n\", cgtest_exp_, cgtest_act_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            return; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_EXPECT_EQ_PTR =
    "#define EXPECT_EQ_PTR(expected, actual) \\\n"
    "    do { \\\n"
    "        const void *cgtest_exp_ = (const void *)(expected); \\\n"
    "        const void *cgtest_act_ = (const void *)(actual); \\\n"
    "        if (cgtest_exp_ != cgtest_act_) { \\\n";

static const char *const CGTEST_H_TEMPLATE_EXPECT_EQ_PTR2 =
    "            fprintf(stderr, \"%s:%d: FAIL: EXPECT_EQ_PTR(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \\\n"
    "            fprintf(stderr, \"  expected: %p\\n  actual:   %p\\n\", cgtest_exp_, cgtest_act_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_ASSERT_EQ_PTR =
    "#define ASSERT_EQ_PTR(expected, actual) \\\n"
    "    do { \\\n"
    "        const void *cgtest_exp_ = (const void *)(expected); \\\n"
    "        const void *cgtest_act_ = (const void *)(actual); \\\n"
    "        if (cgtest_exp_ != cgtest_act_) { \\\n";

static const char *const CGTEST_H_TEMPLATE_ASSERT_EQ_PTR2 =
    "            fprintf(stderr, \"%s:%d: FAIL: ASSERT_EQ_PTR(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \\\n"
    "            fprintf(stderr, \"  expected: %p\\n  actual:   %p\\n\", cgtest_exp_, cgtest_act_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            return; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

/* Content comparison via strcmp(), not pointer equality - two equal
 * C-strings stored at different addresses must still count as equal.
 * Same reason GoogleTest has EXPECT_STREQ separate from EXPECT_EQ. */
static const char *const CGTEST_H_TEMPLATE_EXPECT_EQ_STR =
    "#define EXPECT_EQ_STR(expected, actual) \\\n"
    "    do { \\\n"
    "        const char *cgtest_exp_ = (expected); \\\n"
    "        const char *cgtest_act_ = (actual); \\\n"
    "        if (strcmp(cgtest_exp_, cgtest_act_) != 0) { \\\n";

static const char *const CGTEST_H_TEMPLATE_EXPECT_EQ_STR2 =
    "            fprintf(stderr, \"%s:%d: FAIL: EXPECT_EQ_STR(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \\\n"
    "            cgtest_print_str_field(\"  expected: \", cgtest_exp_); \\\n"
    "            cgtest_print_str_field(\"  actual:   \", cgtest_act_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_ASSERT_EQ_STR =
    "#define ASSERT_EQ_STR(expected, actual) \\\n"
    "    do { \\\n"
    "        const char *cgtest_exp_ = (expected); \\\n"
    "        const char *cgtest_act_ = (actual); \\\n"
    "        if (strcmp(cgtest_exp_, cgtest_act_) != 0) { \\\n";

static const char *const CGTEST_H_TEMPLATE_ASSERT_EQ_STR2 =
    "            fprintf(stderr, \"%s:%d: FAIL: ASSERT_EQ_STR(%s, %s)\\n\", \\\n"
    "                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \\\n"
    "            cgtest_print_str_field(\"  expected: \", cgtest_exp_); \\\n"
    "            cgtest_print_str_field(\"  actual:   \", cgtest_act_); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            return; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_FOOTER =
    "#endif /* CGTEST_H */\n";

static CGTestCreateResult cgtest_create_fail(const char *message)
{
    CGTestCreateResult result;
    result.ok = 0;
    result.error = cmsg_dup(message, strlen(message));
    return result;
}

/* The variadic "..." parts (each a "const char *", terminated by a
 * NULL sentinel) are written back to back into one file - lets a
 * template be split across as many string literals as needed (see
 * CGTEST_H_TEMPLATE_HEAD1 and friends) without ever concatenating
 * them in memory. */
static int cgtest_create_write_file(const char *path, char *error_buf, size_t error_buf_size, ...)
{
    FILE *f;
    va_list args;
    const char *part;
    size_t len;

    f = fopen(path, "wb");
    if (f == NULL) {
        cmsg_build(error_buf, error_buf_size, "could not create ", path, strlen(path), "");
        return 0;
    }

    va_start(args, error_buf_size);
    for (part = va_arg(args, const char *); part != NULL; part = va_arg(args, const char *)) {
        len = strlen(part);
        if (fwrite(part, 1, len, f) != len) {
            va_end(args);
            fclose(f);
            cmsg_build(error_buf, error_buf_size, "could not write ", path, strlen(path), "");
            return 0;
        }
    }
    va_end(args);

    fclose(f);
    return 1;
}

CGTestCreateResult cgtest_create_run(const char *dir)
{
    CGTestCreateResult result;
    char cwd[CGTEST_CREATE_PATH_SCRATCH];
    char abs_dir_scratch[CGTEST_CREATE_PATH_SCRATCH];
    char config_scratch[CGTEST_CREATE_PATH_SCRATCH];
    char header_scratch[CGTEST_CREATE_PATH_SCRATCH];
    CPath abs_dir;
    CPath config_path;
    CPath header_path;
    struct stat st;
    char error_buf[CGTEST_CREATE_ERROR_BUFSZ];

    if (CGTEST_GETCWD(cwd, sizeof(cwd)) == NULL) {
        return cgtest_create_fail("could not determine the current working directory");
    }

    abs_dir = cpath_join(abs_dir_scratch, sizeof(abs_dir_scratch), cwd, dir);

    if (stat(abs_dir.data, &st) != 0) {
        if (CGTEST_MKDIR(abs_dir.data) != 0) {
            cmsg_build(error_buf, sizeof(error_buf), "could not create directory ", abs_dir.data, abs_dir.length, "");
            return cgtest_create_fail(error_buf);
        }
    } else if (!S_ISDIR(st.st_mode)) {
        cmsg_build(error_buf, sizeof(error_buf), "not a directory: ", abs_dir.data, abs_dir.length, "");
        return cgtest_create_fail(error_buf);
    }

    config_path = cpath_join(config_scratch, sizeof(config_scratch), abs_dir.data, "cgtest-config.json");

    if (stat(config_path.data, &st) == 0) {
        cmsg_build(error_buf, sizeof(error_buf), "cgtest-config.json already exists: ",
                   config_path.data, config_path.length, "");
        return cgtest_create_fail(error_buf);
    }

    header_path = cpath_join(header_scratch, sizeof(header_scratch), abs_dir.data, "cgtest.h");

    if (!cgtest_create_write_file(config_path.data, error_buf, sizeof(error_buf),
                                   CGTEST_CONFIG_TEMPLATE, (const char *)NULL)) {
        return cgtest_create_fail(error_buf);
    }
    if (!cgtest_create_write_file(header_path.data, error_buf, sizeof(error_buf),
                                   CGTEST_H_TEMPLATE_HEAD1, CGTEST_H_TEMPLATE_HEAD1B, CGTEST_H_TEMPLATE_HEAD2,
                                   CGTEST_H_TEMPLATE_RELPATH1, CGTEST_H_TEMPLATE_RELPATH2,
                                   CGTEST_H_TEMPLATE_STRFIELD1, CGTEST_H_TEMPLATE_STRFIELD2,
                                   CGTEST_H_TEMPLATE_STRFIELD3, CGTEST_H_TEMPLATE_STRFIELD4,
                                   CGTEST_H_TEMPLATE_EXPECT_TRUE, CGTEST_H_TEMPLATE_EXPECT_FALSE,
                                   CGTEST_H_TEMPLATE_ASSERT_TRUE, CGTEST_H_TEMPLATE_ASSERT_FALSE,
                                   CGTEST_H_TEMPLATE_EXPECT_EQ_INT, CGTEST_H_TEMPLATE_EXPECT_EQ_INT2,
                                   CGTEST_H_TEMPLATE_ASSERT_EQ_INT, CGTEST_H_TEMPLATE_ASSERT_EQ_INT2,
                                   CGTEST_H_TEMPLATE_EXPECT_EQ_UINT, CGTEST_H_TEMPLATE_EXPECT_EQ_UINT2,
                                   CGTEST_H_TEMPLATE_ASSERT_EQ_UINT, CGTEST_H_TEMPLATE_ASSERT_EQ_UINT2,
                                   CGTEST_H_TEMPLATE_EXPECT_EQ_DOUBLE, CGTEST_H_TEMPLATE_EXPECT_EQ_DOUBLE2,
                                   CGTEST_H_TEMPLATE_ASSERT_EQ_DOUBLE, CGTEST_H_TEMPLATE_ASSERT_EQ_DOUBLE2,
                                   CGTEST_H_TEMPLATE_EXPECT_EQ_PTR, CGTEST_H_TEMPLATE_EXPECT_EQ_PTR2,
                                   CGTEST_H_TEMPLATE_ASSERT_EQ_PTR, CGTEST_H_TEMPLATE_ASSERT_EQ_PTR2,
                                   CGTEST_H_TEMPLATE_EXPECT_EQ_STR, CGTEST_H_TEMPLATE_EXPECT_EQ_STR2,
                                   CGTEST_H_TEMPLATE_ASSERT_EQ_STR, CGTEST_H_TEMPLATE_ASSERT_EQ_STR2,
                                   CGTEST_H_TEMPLATE_FOOTER,
                                   (const char *)NULL)) {
        return cgtest_create_fail(error_buf);
    }

    result.ok = 1;
    result.error = NULL;
    return result;
}

void cgtest_create_free(CGTestCreateResult *result)
{
    free(result->error);
    result->error = NULL;
}
