/* cgtest_create.c - see cgtest_create.h.
 *
 * "dir" is always a directory, never a file path - cgtest-config.json
 * and cgtest.h are always written as "dir/cgtest-config.json" and
 * "dir/cgtest.h". "dir" is resolved to an absolute path the same way
 * cgtest_config_load() does (getcwd() + cpath_join()), created if it
 * doesn't exist yet (mkdir() - "dir"'s own parent must already exist;
 * this does not create intermediate directories), then the two
 * templates are written inside it.
 */
#include "cgtest_create.h"
#include "cpath.h"
#include "cmsg.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#ifdef _WIN32
#include <direct.h>
#define CGTEST_GETCWD _getcwd
#define CGTEST_MKDIR(path) _mkdir(path)
#else
#include <unistd.h>
#define CGTEST_GETCWD getcwd
#define CGTEST_MKDIR(path) mkdir(path, 0755)
#endif

#define CGTEST_CREATE_PATH_SCRATCH 4096
#define CGTEST_CREATE_ERROR_BUFSZ  256

static const char *const CGTEST_CONFIG_TEMPLATE =
    "{\n"
    "    \"compiler_command\": \"gcc -std=c99 -O3\",\n"
    "    \"include_paths\": [\n"
    "        \"./include\",\n"
    "        \"./third_party\",\n"
    "        \"/usr/local/include\"\n"
    "    ],\n"
    "    \"source_files\": [\n"
    "        \"./src/foo.c\",\n"
    "        \"./src/bar.c\",\n"
    "        \"./src/baz.c\"\n"
    "    ],\n"
    "    \"output_path\": \"./build\",\n"
    "    \"test_directories\": [\n"
    "        \"./tests\",\n"
    "        \"./unittests\",\n"
    "        \"/home/user/project/tests\"\n"
    "    ]\n"
    "}\n";

/* Split into two literals rather than one: ISO C90 compilers are only
 * required to support string literals up to 509 chars (after adjacent
 * concatenation), and the combined template exceeds that. */
static const char *const CGTEST_H_TEMPLATE_HEAD =
    "#ifndef CGTEST_H\n"
    "#define CGTEST_H\n"
    "\n"
    "/* Generated by \"cgtest --create\". Test functions have the form\n"
    " * \"void test_<name>(void) { ... }\"; CGTEST_CHECK() reports a failed\n"
    " * assertion and returns from the current test function. The\n"
    " * generated runner reads cgtest_failed after calling each test to\n"
    " * decide pass/fail, resetting it to 0 first - a plain \"void\"\n"
    " * signature keeps test files C89-portable (no <stdbool.h>). */\n"
    "\n"
    "#include <stdio.h>\n"
    "\n"
    "extern int cgtest_failed;\n"
    "\n";

static const char *const CGTEST_H_TEMPLATE_TAIL =
    "#define CGTEST_CHECK(cond) \\\n"
    "    do { \\\n"
    "        if (!(cond)) { \\\n"
    "            fprintf(stderr, \"  FAIL %s:%d: %s\\n\", __FILE__, __LINE__, #cond); \\\n"
    "            cgtest_failed = 1; \\\n"
    "            return; \\\n"
    "        } \\\n"
    "    } while (0)\n"
    "\n"
    "#endif /* CGTEST_H */\n";

static CGTestCreateResult cgtest_create_fail(const char *message)
{
    CGTestCreateResult result;
    result.ok = 0;
    result.error = cmsg_dup(message, strlen(message));
    return result;
}

/* "part1"/"part2" are written back to back into one file - lets a
 * template be split across multiple string literals (see
 * CGTEST_H_TEMPLATE_HEAD / _TAIL) without ever concatenating them in
 * memory. "part2" may be NULL if the template is a single literal. */
static int cgtest_create_write_file(const char *path, const char *part1, const char *part2,
                                     char *error_buf, size_t error_buf_size)
{
    FILE *f;
    size_t len;

    f = fopen(path, "wb");
    if (f == NULL) {
        cmsg_build(error_buf, error_buf_size, "could not create ", path, strlen(path), "");
        return 0;
    }

    len = strlen(part1);
    if (fwrite(part1, 1, len, f) != len) {
        fclose(f);
        cmsg_build(error_buf, error_buf_size, "could not write ", path, strlen(path), "");
        return 0;
    }

    if (part2 != NULL) {
        len = strlen(part2);
        if (fwrite(part2, 1, len, f) != len) {
            fclose(f);
            cmsg_build(error_buf, error_buf_size, "could not write ", path, strlen(path), "");
            return 0;
        }
    }

    fclose(f);
    return 1;
}

CGTestCreateResult cgtest_create_run(const char *dir)
{
    CGTestCreateResult result;
    char cwd[CGTEST_CREATE_PATH_SCRATCH];
    char abs_dir_scratch[CGTEST_CREATE_PATH_SCRATCH];
    char config_scratch[CGTEST_CREATE_PATH_SCRATCH];
    char header_scratch[CGTEST_CREATE_PATH_SCRATCH];
    CPath abs_dir;
    CPath config_path;
    CPath header_path;
    struct stat st;
    char error_buf[CGTEST_CREATE_ERROR_BUFSZ];

    if (CGTEST_GETCWD(cwd, sizeof(cwd)) == NULL) {
        return cgtest_create_fail("could not determine the current working directory");
    }

    abs_dir = cpath_join(abs_dir_scratch, sizeof(abs_dir_scratch), cwd, dir);

    if (stat(abs_dir.data, &st) != 0) {
        if (CGTEST_MKDIR(abs_dir.data) != 0) {
            cmsg_build(error_buf, sizeof(error_buf), "could not create directory ", abs_dir.data, abs_dir.length, "");
            return cgtest_create_fail(error_buf);
        }
    } else if (!S_ISDIR(st.st_mode)) {
        cmsg_build(error_buf, sizeof(error_buf), "not a directory: ", abs_dir.data, abs_dir.length, "");
        return cgtest_create_fail(error_buf);
    }

    config_path = cpath_join(config_scratch, sizeof(config_scratch), abs_dir.data, "cgtest-config.json");

    if (stat(config_path.data, &st) == 0) {
        cmsg_build(error_buf, sizeof(error_buf), "cgtest-config.json already exists: ",
                   config_path.data, config_path.length, "");
        return cgtest_create_fail(error_buf);
    }

    header_path = cpath_join(header_scratch, sizeof(header_scratch), abs_dir.data, "cgtest.h");

    if (!cgtest_create_write_file(config_path.data, CGTEST_CONFIG_TEMPLATE, NULL, error_buf, sizeof(error_buf))) {
        return cgtest_create_fail(error_buf);
    }
    if (!cgtest_create_write_file(header_path.data, CGTEST_H_TEMPLATE_HEAD, CGTEST_H_TEMPLATE_TAIL,
                                   error_buf, sizeof(error_buf))) {
        return cgtest_create_fail(error_buf);
    }

    result.ok = 1;
    result.error = NULL;
    return result;
}

void cgtest_create_free(CGTestCreateResult *result)
{
    free(result->error);
    result->error = NULL;
}
