/* cgtest_runner.c - see cgtest_runner.h.
 *
 * cgtest_runner_generate_source() is pure string-building (see
 * CGTestRunnerBuf below, a small growable buffer local to this file -
 * unlike cmsg.h's fixed-size messages, a generated C source file or a
 * compiler command line has no reasonable upper bound, so this one
 * grows). cgtest_runner_run() is everything around it: discovering
 * test files/functions, writing the generated source to disk, and
 * shelling out to the compiler and the resulting binary via system() -
 * acceptable here since compiler_command comes from the user's own
 * trusted cgtest-project.json, the same trust boundary cgtest already
 * crosses by running that compiler at all.
 */
#include "cgtest_runner.h"
#include "ctestfiles.h"
#include "cpath.h"
#include "cmsg.h"
#include "clexer.h"
#include "ctimer.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#ifdef _WIN32
#include <direct.h>
#define CGTEST_RUNNER_MKDIR(path) _mkdir(path)
#define CGTEST_RUNNER_EXE_SUFFIX  ".exe"
static int cgtest_runner_decode_exit(int system_result)
{
    return system_result;
}
#else
#include <unistd.h>
#include <sys/wait.h>
#define CGTEST_RUNNER_MKDIR(path) mkdir(path, 0755)
#define CGTEST_RUNNER_EXE_SUFFIX  ""
static int cgtest_runner_decode_exit(int system_result)
{
    if (system_result == -1) {
        return -1;
    }
    if (WIFEXITED(system_result)) {
        return WEXITSTATUS(system_result);
    }
    return 1;
}
#endif

/* MSVC's <sys/stat.h> defines S_IFDIR/S_IFMT but not the S_ISDIR()
 * convenience macro POSIX builds already get for free. */
#ifndef S_ISDIR
#define S_ISDIR(mode) (((mode) & S_IFMT) == S_IFDIR)
#endif

#define CGTEST_RUNNER_PATH_SCRATCH 4096
#define CGTEST_RUNNER_ERROR_BUFSZ  256
#define CGTEST_RUNNER_IDENT_BUFSZ  128

/* A small growable buffer for building unbounded-length text (a
 * generated C source file, or a compiler command line with an
 * arbitrary number of paths) - grows by doubling, like ctestscanner's
 * CTestFunctionList. */
typedef struct {
    char   *data;
    size_t  length;
    size_t  capacity;
} CGTestRunnerBuf;

static int cgtest_runner_buf_init(CGTestRunnerBuf *buf)
{
    buf->capacity = 256;
    buf->length = 0;
    buf->data = (char *)malloc(buf->capacity);
    if (buf->data == NULL) {
        return 0;
    }
    buf->data[0] = '\0';
    return 1;
}

static int cgtest_runner_buf_append(CGTestRunnerBuf *buf, const char *text, size_t text_len)
{
    if (buf->length + text_len + 1 > buf->capacity) {
        size_t new_capacity = buf->capacity;
        char *grown;
        while (new_capacity < buf->length + text_len + 1) {
            new_capacity *= 2;
        }
        grown = (char *)realloc(buf->data, new_capacity);
        if (grown == NULL) {
            return 0;
        }
        buf->data = grown;
        buf->capacity = new_capacity;
    }
    memcpy(buf->data + buf->length, text, text_len);
    buf->length += text_len;
    buf->data[buf->length] = '\0';
    return 1;
}

static int cgtest_runner_buf_append_cstr(CGTestRunnerBuf *buf, const char *text)
{
    return cgtest_runner_buf_append(buf, text, strlen(text));
}

/* Returns a pointer to the filename portion of "path" (everything
 * after its last '/'). Every path this module deals with was built
 * via cpath_join()/cpathlist_register(), which always normalizes to
 * '/' regardless of platform (see cpath.h), so a plain '/' search is
 * enough here - no separate '\\' case is needed. */
static const char *cgtest_runner_basename(const char *path)
{
    const char *slash = strrchr(path, '/');
    return slash != NULL ? slash + 1 : path;
}

char *cgtest_runner_generate_source(const CGTestRunnerFile *files, size_t file_count, const char *compile_command)
{
    CGTestRunnerBuf buf;
    size_t i;
    size_t j;
    size_t k;
    const char **seen_types;
    size_t seen_count;
    size_t total_functions;

    if (!cgtest_runner_buf_init(&buf)) {
        return NULL;
    }

    if (!cgtest_runner_buf_append_cstr(&buf, "/* Generated by cgtest.exe - do not edit. */\n") ||
        !cgtest_runner_buf_append_cstr(&buf, "/* compile: ") ||
        !cgtest_runner_buf_append_cstr(&buf, compile_command) ||
        !cgtest_runner_buf_append_cstr(&buf, " */\n") ||
        !cgtest_runner_buf_append_cstr(&buf,
            "#include <stdio.h>\n"
            /* isatty() is POSIX, not ISO C, so it needs its own header
             * per platform - used below to decide whether the
             * [ RUN ]/[ OK ]/[ FAILED ] lines get ANSI color codes.
             * Same reasoning as GoogleTest's own color detection: color
             * codes are only meaningful on a real terminal, and would
             * otherwise pollute output piped into a log file or an
             * editor's quickfix list. */
            "#ifdef _WIN32\n"
            "#include <io.h>\n"
            "#define CGTEST_ISATTY(fd) _isatty(fd)\n"
            "#else\n"
            "#include <unistd.h>\n"
            "#define CGTEST_ISATTY(fd) isatty(fd)\n"
            "#endif\n"
            "\n"
            "int cgtest_failed = 0;\n"
            /* Set only by ASSERT_* (never EXPECT_*) - see cgtest.h.
             * Checked after setup_<name>(&state) below to decide
             * whether test_<name>(&state) runs at all, matching
             * GoogleTest's SetUp()/TestBody() behavior (specification.md
             * ch.6). */
            "int cgtest_fatal_failed = 0;\n"
            "\n")) {
        goto fail;
    }

    /* Every discovered test_*.c file compiles as its own translation
     * unit (see cgtest_runner_build_compile_command()) - cgtest-runner.c
     * never #includes them, so their own static helpers/globals stay
     * properly file-scoped instead of sharing a namespace with every
     * other test file. What cgtest-runner.c needs from each file
     * instead is declared here: a forward declaration of each distinct
     * fixture type (see below), then an "extern" for every discovered
     * function.
     *
     * Fixture types are forward-declared as incomplete ("typedef struct
     * T T;") rather than #include'd or copied in full - cgtest-runner.c
     * only ever holds/passes a "T *"/"T **", never allocates or
     * dereferences a "T" by value, so it never needs T's real
     * definition (see specification.md ch.6 "Generated code"). This
     * requires the test file's own definition to tag its struct to
     * match the typedef name (e.g. "typedef struct T { ... } T;", not
     * the tag-less "typedef struct { ... } T;") - only then are the two
     * separately-compiled "T"s the same type by C's own cross-
     * translation-unit compatibility rule, not just two same-spelled
     * but distinct opaque types that happen to work by ABI accident.
     *
     * Deduplicated across every file/function (counted via
     * "total_functions" as an upper bound for the scratch array below)
     * - the same type name forward-declared twice is a hard error under
     * strict C89 -pedantic-errors (that redundant-typedef allowance is
     * C11-only), and two *different* fixture tests sharing a type name
     * is an ordinary, expected case (e.g. every test in one file using
     * the same fixture). */
    total_functions = 0;
    for (i = 0; i < file_count; i++) {
        total_functions += files[i].function_count;
    }

    seen_types = NULL;
    if (total_functions > 0) {
        seen_types = (const char **)malloc(total_functions * sizeof(const char *));
        if (seen_types == NULL) {
            goto fail;
        }
    }

    seen_count = 0;
    for (i = 0; i < file_count; i++) {
        for (j = 0; j < files[i].function_count; j++) {
            const char *fixture_type = files[i].functions[j].fixture_type;
            int already_seen;

            if (fixture_type == NULL) {
                continue;
            }

            already_seen = 0;
            for (k = 0; k < seen_count; k++) {
                if (strcmp(seen_types[k], fixture_type) == 0) {
                    already_seen = 1;
                    break;
                }
            }
            if (already_seen) {
                continue;
            }

            if (!cgtest_runner_buf_append_cstr(&buf, "typedef struct ") ||
                !cgtest_runner_buf_append_cstr(&buf, fixture_type) ||
                !cgtest_runner_buf_append_cstr(&buf, " ") ||
                !cgtest_runner_buf_append_cstr(&buf, fixture_type) ||
                !cgtest_runner_buf_append_cstr(&buf, ";\n")) {
                free(seen_types);
                goto fail;
            }
            seen_types[seen_count++] = fixture_type;
        }
    }
    free(seen_types);

    if (seen_count > 0 && !cgtest_runner_buf_append_cstr(&buf, "\n")) {
        goto fail;
    }

    for (i = 0; i < file_count; i++) {
        for (j = 0; j < files[i].function_count; j++) {
            const char *name = files[i].functions[j].name;
            const char *fixture_type = files[i].functions[j].fixture_type;

            if (fixture_type == NULL) {
                if (!cgtest_runner_buf_append_cstr(&buf, "extern void ") ||
                    !cgtest_runner_buf_append_cstr(&buf, name) ||
                    !cgtest_runner_buf_append_cstr(&buf, "(void);\n")) {
                    goto fail;
                }
            } else {
                /* "<name>" here is "name" with its "test_" prefix
                 * stripped (guaranteed present: ctestscanner_find()
                 * only ever reports functions matching "test_<name>").
                 * setup_<name> takes a "T **" (out-param, not a return
                 * value) specifically so it stays void-returning -
                 * EXPECT_* and ASSERT_* (see cgtest.h) work inside it
                 * completely unchanged, including ASSERT_*'s early
                 * "return;", which wouldn't type-check in a function
                 * declared to return "T *". */
                const char *suffix = name + 5;
                int has_teardown = files[i].functions[j].has_teardown;

                if (!cgtest_runner_buf_append_cstr(&buf, "extern void setup_") ||
                    !cgtest_runner_buf_append_cstr(&buf, suffix) ||
                    !cgtest_runner_buf_append_cstr(&buf, "(") ||
                    !cgtest_runner_buf_append_cstr(&buf, fixture_type) ||
                    !cgtest_runner_buf_append_cstr(&buf, " **state);\n") ||
                    !cgtest_runner_buf_append_cstr(&buf, "extern void ") ||
                    !cgtest_runner_buf_append_cstr(&buf, name) ||
                    !cgtest_runner_buf_append_cstr(&buf, "(") ||
                    !cgtest_runner_buf_append_cstr(&buf, fixture_type) ||
                    !cgtest_runner_buf_append_cstr(&buf, " *state);\n")) {
                    goto fail;
                }

                if (has_teardown) {
                    if (!cgtest_runner_buf_append_cstr(&buf, "extern void teardown_") ||
                        !cgtest_runner_buf_append_cstr(&buf, suffix) ||
                        !cgtest_runner_buf_append_cstr(&buf, "(") ||
                        !cgtest_runner_buf_append_cstr(&buf, fixture_type) ||
                        !cgtest_runner_buf_append_cstr(&buf, " *state);\n")) {
                        goto fail;
                    }
                }
            }
        }
    }

    if (!cgtest_runner_buf_append_cstr(&buf,
            "\n"
            "int main(void)\n"
            "{\n"
            "    int total = 0;\n"
            "    int failed = 0;\n"
            "    int file_total = 0;\n"
            "    int file_failed = 0;\n"
            "    const char *cgtest_green;\n"
            "    const char *cgtest_red;\n"
            "    const char *cgtest_reset;\n"
            "\n"
            /* Without this, stdout is fully block-buffered whenever it
             * isn't a tty (piped, redirected, or captured by an
             * editor's :make) - every printf() below would then sit
             * buffered until exit while stderr's FAIL: lines (from
             * EXPECT_TRUE/EXPECT_FALSE/ASSERT_TRUE/ASSERT_FALSE)
             * appear immediately, making failures print out of
             * chronological order. */
            "    setvbuf(stdout, NULL, _IOLBF, 0);\n"
            "    cgtest_green = CGTEST_ISATTY(1) ? \"\\x1b[32m\" : \"\";\n"
            "    cgtest_red   = CGTEST_ISATTY(1) ? \"\\x1b[31m\" : \"\";\n"
            "    cgtest_reset = CGTEST_ISATTY(1) ? \"\\x1b[0m\"  : \"\";\n"
            "\n")) {
        goto fail;
    }

    for (i = 0; i < file_count; i++) {
        if (files[i].function_count == 0) {
            continue;
        }

        if (!cgtest_runner_buf_append_cstr(&buf, "    file_total = 0;\n    file_failed = 0;\n") ||
            !cgtest_runner_buf_append_cstr(&buf, "    printf(\"== ") ||
            !cgtest_runner_buf_append_cstr(&buf, cgtest_runner_basename(files[i].label)) ||
            !cgtest_runner_buf_append_cstr(&buf, " ==\\n\");\n")) {
            goto fail;
        }

        for (j = 0; j < files[i].function_count; j++) {
            const char *name = files[i].functions[j].name;
            const char *fixture_type = files[i].functions[j].fixture_type;
            /* Printed before the call, not after: whether the test
             * passed isn't known until it's actually run, so this
             * announces which test any FAIL: lines below belong to -
             * same reason GoogleTest has "[ RUN      ]" ahead of its
             * "[       OK ]"/"[  FAILED  ]" verdict rather than trying
             * to print the verdict first. Bracket text/width matches
             * GoogleTest's own literally, not just the general idea. */
            /* Color wraps only the bracket token itself, matching
             * GoogleTest exactly: its PrettyUnitTestResultPrinter
             * colors "[ RUN      ]"/"[       OK ]"/"[  FAILED  ]" but
             * prints the test name after it in the default color. */
            if (!cgtest_runner_buf_append_cstr(&buf, "    printf(\"%s[ RUN      ]%s ") ||
                !cgtest_runner_buf_append_cstr(&buf, name) ||
                !cgtest_runner_buf_append_cstr(&buf, "\\n\", cgtest_green, cgtest_reset);\n    total++;\n    file_total++;\n    cgtest_failed = 0;\n    cgtest_fatal_failed = 0;\n")) {
                goto fail;
            }

            if (fixture_type == NULL) {
                if (!cgtest_runner_buf_append_cstr(&buf, "    ") ||
                    !cgtest_runner_buf_append_cstr(&buf, name) ||
                    !cgtest_runner_buf_append_cstr(&buf, "();\n")) {
                    goto fail;
                }
            } else {
                /* setup_<name> (mandatory) and, if present,
                 * teardown_<name> (optional - specification.md ch.6;
                 * a fixture with nothing to release just omits it,
                 * rather than requiring a no-op function) wrap this
                 * call. "<name>" here is "name" with its "test_" prefix
                 * stripped (guaranteed present: ctestscanner_find()
                 * only ever reports functions matching "test_<name>").
                 * "state" starts NULL and is populated by setup_<name>
                 * itself (an out-param, not a return value - see the
                 * extern declaration above for why); cgtest-runner.c
                 * never allocates or frees *state, only ever holds the
                 * pointer setup_<name> hands back - if setup_<name>
                 * never assigns it (e.g. a fatal ASSERT_* failure before
                 * doing so), "state" stays the well-defined NULL it
                 * started as, safe to pass to a present teardown_<name>.
                 * test_<name>(state) is skipped when setup_<name> hit a
                 * fatal (ASSERT_*) failure, matching GoogleTest's
                 * SetUp()/TestBody() behavior; a present
                 * teardown_<name>(state) still always runs regardless. */
                const char *suffix = name + 5;
                int has_teardown = files[i].functions[j].has_teardown;

                if (!cgtest_runner_buf_append_cstr(&buf, "    {\n        ") ||
                    !cgtest_runner_buf_append_cstr(&buf, fixture_type) ||
                    !cgtest_runner_buf_append_cstr(&buf, " *state = NULL;\n        setup_") ||
                    !cgtest_runner_buf_append_cstr(&buf, suffix) ||
                    !cgtest_runner_buf_append_cstr(&buf, "(&state);\n        if (!cgtest_fatal_failed) {\n            ") ||
                    !cgtest_runner_buf_append_cstr(&buf, name) ||
                    !cgtest_runner_buf_append_cstr(&buf, "(state);\n        }\n")) {
                    goto fail;
                }

                if (has_teardown) {
                    if (!cgtest_runner_buf_append_cstr(&buf, "        teardown_") ||
                        !cgtest_runner_buf_append_cstr(&buf, suffix) ||
                        !cgtest_runner_buf_append_cstr(&buf, "(state);\n")) {
                        goto fail;
                    }
                }

                if (!cgtest_runner_buf_append_cstr(&buf, "    }\n")) {
                    goto fail;
                }
            }

            if (!cgtest_runner_buf_append_cstr(&buf, "    if (!cgtest_failed) {\n        printf(\"%s[       OK ]%s ") ||
                !cgtest_runner_buf_append_cstr(&buf, name) ||
                !cgtest_runner_buf_append_cstr(&buf, "\\n\", cgtest_green, cgtest_reset);\n    } else {\n        printf(\"%s[  FAILED  ]%s ") ||
                !cgtest_runner_buf_append_cstr(&buf, name) ||
                !cgtest_runner_buf_append_cstr(&buf, "\\n\", cgtest_red, cgtest_reset);\n        failed++;\n        file_failed++;\n    }\n")) {
                goto fail;
            }
        }

        if (!cgtest_runner_buf_append_cstr(&buf,
                "    printf(\"             %s%d/%d passed%s\\n\\n\", file_failed == 0 ? cgtest_green : cgtest_red, "
                "file_total - file_failed, file_total, cgtest_reset);\n\n")) {
            goto fail;
        }
    }

    if (!cgtest_runner_buf_append_cstr(&buf,
            "    printf(\"%stotal %d/%d tests passed%s\\n\", failed == 0 ? cgtest_green : cgtest_red, "
            "total - failed, total, cgtest_reset);\n"
            "    return failed == 0 ? 0 : 1;\n"
            "}\n")) {
        goto fail;
    }

    return buf.data;

fail:
    free(buf.data);
    return NULL;
}

static void cgtest_runner_set_error(CGTestRunResult *result, const char *message)
{
    result->ok = 0;
    result->error = cmsg_dup(message, strlen(message));
}

/* Reads "path" whole into a malloc'd, NUL-terminated buffer, setting
 * *out_length to the byte count read (excluding the NUL). Returns
 * NULL on any I/O or allocation failure. */
static char *cgtest_runner_read_file(const char *path, size_t *out_length)
{
    FILE *f;
    long size;
    char *buffer;
    size_t read_count;

    f = fopen(path, "rb");
    if (f == NULL) {
        return NULL;
    }

    if (fseek(f, 0, SEEK_END) != 0 || (size = ftell(f)) < 0 || fseek(f, 0, SEEK_SET) != 0) {
        fclose(f);
        return NULL;
    }

    buffer = (char *)malloc((size_t)size + 1);
    if (buffer == NULL) {
        fclose(f);
        return NULL;
    }

    read_count = fread(buffer, 1, (size_t)size, f);
    fclose(f);
    if (read_count != (size_t)size) {
        free(buffer);
        return NULL;
    }
    buffer[size] = '\0';

    *out_length = (size_t)size;
    return buffer;
}

/* Every discovered test_*.c file (files[i].label) is passed as its own
 * source argument, the same way project->source_files are - each
 * compiles as its own translation unit, matching what
 * cgtest_runner_generate_source() now assumes (an "extern" declaration
 * per function, not an #include). Every test_directories entry is
 * still added as its own include flag too - not for resolving the test
 * files themselves anymore, but so a test file's own #include of a
 * sibling header elsewhere in test_directories still keeps working. */
char *cgtest_runner_build_compile_command(const CGTestProject *project, const CGTestRunnerFile *files, size_t file_count,
                                           const char *runner_c_path, const char *runner_bin_path)
{
    CGTestRunnerBuf buf;
    size_t i;
    const char *include_flag = project->msvc ? " /I\"" : " -I\"";

    if (!cgtest_runner_buf_init(&buf)) {
        return NULL;
    }

    if (!cgtest_runner_buf_append_cstr(&buf, project->compiler_command)) {
        goto fail;
    }

    for (i = 0; i < project->include_paths.count; i++) {
        if (!cgtest_runner_buf_append_cstr(&buf, include_flag) ||
            !cgtest_runner_buf_append_cstr(&buf, project->include_paths.entries[i]) ||
            !cgtest_runner_buf_append_cstr(&buf, "\"")) {
            goto fail;
        }
    }
    for (i = 0; i < project->test_directories.count; i++) {
        if (!cgtest_runner_buf_append_cstr(&buf, include_flag) ||
            !cgtest_runner_buf_append_cstr(&buf, project->test_directories.entries[i]) ||
            !cgtest_runner_buf_append_cstr(&buf, "\"")) {
            goto fail;
        }
    }
    for (i = 0; i < project->source_files.count; i++) {
        if (!cgtest_runner_buf_append_cstr(&buf, " \"") ||
            !cgtest_runner_buf_append_cstr(&buf, project->source_files.entries[i]) ||
            !cgtest_runner_buf_append_cstr(&buf, "\"")) {
            goto fail;
        }
    }
    for (i = 0; i < file_count; i++) {
        if (!cgtest_runner_buf_append_cstr(&buf, " \"") ||
            !cgtest_runner_buf_append_cstr(&buf, files[i].label) ||
            !cgtest_runner_buf_append_cstr(&buf, "\"")) {
            goto fail;
        }
    }
    if (!cgtest_runner_buf_append_cstr(&buf, " \"") ||
        !cgtest_runner_buf_append_cstr(&buf, runner_c_path) ||
        !cgtest_runner_buf_append_cstr(&buf, "\"")) {
        goto fail;
    }
    if (project->msvc) {
        /* cl.exe has no "-o" - the output name is set via "/Fe:path",
         * directly adjacent to the flag, no space before the quote. */
        if (!cgtest_runner_buf_append_cstr(&buf, " /Fe:\"") ||
            !cgtest_runner_buf_append_cstr(&buf, runner_bin_path) ||
            !cgtest_runner_buf_append_cstr(&buf, "\"")) {
            goto fail;
        }
    } else {
        if (!cgtest_runner_buf_append_cstr(&buf, " -o \"") ||
            !cgtest_runner_buf_append_cstr(&buf, runner_bin_path) ||
            !cgtest_runner_buf_append_cstr(&buf, "\"")) {
            goto fail;
        }
    }

    return buf.data;

fail:
    free(buf.data);
    return NULL;
}

/* Returns 1 if "source" tokenizes to an identifier token spelled
 * exactly "name" anywhere in it, 0 otherwise. Used only for the
 * existence-only fixture check below - it does not distinguish a
 * function definition from a declaration, a call, or any other use,
 * since specification.md ch.6 "Validation before invoking the
 * compiler" only asks that setup_<name>/teardown_<name> exist
 * somewhere, leaving everything else (signature match included) to
 * the C compiler itself. */
static int cgtest_runner_source_has_identifier(const char *source, size_t length, const char *name)
{
    CLexer lexer;
    CToken token;
    size_t name_len = strlen(name);

    clexer_init(&lexer, source, length);
    token = clexer_next_token(&lexer);
    while (token.type != CTOK_EOF) {
        if (token.type == CTOK_IDENTIFIER && token.length == name_len && memcmp(token.start, name, name_len) == 0) {
            return 1;
        }
        token = clexer_next_token(&lexer);
    }
    return 0;
}

static int cgtest_runner_any_file_has_identifier(char *const *contents, const size_t *lengths, size_t count, const char *name)
{
    size_t i;
    for (i = 0; i < count; i++) {
        if (cgtest_runner_source_has_identifier(contents[i], lengths[i], name)) {
            return 1;
        }
    }
    return 0;
}

/* Before compiling, every discovered test_ function with a fixture
 * parameter (CTestFunction::fixture_type != NULL) must have a
 * setup_<name> identifier present somewhere among "contents" (every
 * discovered test_*.c file's raw source, not just the ones with their
 * own test_ functions - a shared fixture file might have neither) -
 * otherwise this fails with a clear cgtest-level message instead of
 * surfacing as a raw linker error once the compiler runs. Existence-
 * only (see cgtest_runner_source_has_identifier() above) - a
 * parameter-type mismatch is left entirely to the C compiler's own
 * type checking.
 *
 * teardown_<name> is optional (specification.md ch.6) - unlike a
 * missing setup_<name>, "*state" is never read before setup_<name>
 * runs, so there is nothing unsafe about skipping a teardown that
 * doesn't exist. Rather than erroring, this records whether it exists
 * in fn->has_teardown for cgtest_runner_generate_source() to act on.
 *
 * Returns 1 and leaves "result" untouched on success; returns 0 with
 * "result" set to the failure if any setup_<name> is missing. */
static int cgtest_runner_check_fixtures(CGTestRunnerFile *runner_files, size_t runner_file_count,
                                         char *const *contents, const size_t *lengths, size_t file_count,
                                         CGTestRunResult *result)
{
    size_t i;
    size_t j;

    for (i = 0; i < runner_file_count; i++) {
        for (j = 0; j < runner_files[i].function_count; j++) {
            CTestFunction *fn = &runner_files[i].functions[j];
            const char *suffix;
            char ident[CGTEST_RUNNER_IDENT_BUFSZ];
            char msg[CGTEST_RUNNER_ERROR_BUFSZ];

            if (fn->fixture_type == NULL) {
                continue;
            }
            /* "test_" prefix guaranteed by ctestscanner_find(). */
            suffix = fn->name + 5;

            cmsg_build(ident, sizeof(ident), "setup_", suffix, strlen(suffix), "");
            if (!cgtest_runner_any_file_has_identifier(contents, lengths, file_count, ident)) {
                cmsg_build(msg, sizeof(msg), "missing fixture setup function: ", ident, strlen(ident), "");
                cgtest_runner_set_error(result, msg);
                return 0;
            }

            cmsg_build(ident, sizeof(ident), "teardown_", suffix, strlen(suffix), "");
            fn->has_teardown = cgtest_runner_any_file_has_identifier(contents, lengths, file_count, ident);
        }
    }
    return 1;
}

CGTestRunResult cgtest_runner_run(const CGTestProject *project)
{
    CGTestRunResult result;
    CPathList test_files;
    CGTestRunnerFile *runner_files;
    size_t runner_file_count;
    char **file_contents;
    size_t *file_lengths;
    size_t file_contents_count;
    char *source;
    char runner_c_scratch[CGTEST_RUNNER_PATH_SCRATCH];
    char runner_bin_scratch[CGTEST_RUNNER_PATH_SCRATCH];
    CPath runner_c_path;
    CPath runner_bin_path;
    struct stat st;
    FILE *f;
    char *compile_cmd;
    int system_result;
    size_t i;
    double t_start;
    double t_phase;
    double t_now;
    double scan_ms;
    double generate_ms;
    double compile_ms;
    double run_ms;

    t_start = ctimer_now_ms();
    t_phase = t_start;
    scan_ms = 0.0;
    generate_ms = 0.0;
    compile_ms = 0.0;
    run_ms = 0.0;

    result.ok = 0;
    result.error = NULL;
    result.exit_code = -1;

    cpathlist_init(&test_files);
    runner_files = NULL;
    runner_file_count = 0;
    file_contents = NULL;
    file_lengths = NULL;
    file_contents_count = 0;
    source = NULL;
    compile_cmd = NULL;

    for (i = 0; i < project->test_directories.count; i++) {
        CTestFileScan scan = ctestfiles_scan(project->test_directories.entries[i]);
        size_t j;

        if (!scan.ok) {
            cgtest_runner_set_error(&result, scan.error);
            ctestfiles_free(&scan);
            goto cleanup;
        }

        for (j = 0; j < scan.files.count; j++) {
            if (cpathlist_register(&test_files, "", scan.files.entries[j]) == CPATHLIST_ALLOC_FAILED) {
                cgtest_runner_set_error(&result, "out of memory");
                ctestfiles_free(&scan);
                goto cleanup;
            }
        }
        ctestfiles_free(&scan);
    }

    if (test_files.count == 0) {
        cgtest_runner_set_error(&result, "no test_*.c files found in any test_directories entry");
        goto cleanup;
    }

    runner_files = (CGTestRunnerFile *)malloc(test_files.count * sizeof(CGTestRunnerFile));
    file_contents = (char **)malloc(test_files.count * sizeof(char *));
    file_lengths = (size_t *)malloc(test_files.count * sizeof(size_t));
    if (runner_files == NULL || file_contents == NULL || file_lengths == NULL) {
        cgtest_runner_set_error(&result, "out of memory");
        goto cleanup;
    }

    /* Contents are kept around (not freed right after scanning) so
     * cgtest_runner_check_fixtures() below can search every file's raw
     * text for setup_<name>/teardown_<name> identifiers - freed
     * together with everything else in "cleanup". */
    for (i = 0; i < test_files.count; i++) {
        CTestFunction *functions;
        size_t count;

        file_contents[i] = cgtest_runner_read_file(test_files.entries[i], &file_lengths[i]);
        if (file_contents[i] == NULL) {
            char msg[CGTEST_RUNNER_ERROR_BUFSZ];
            cmsg_build(msg, sizeof(msg), "could not read test file: ", test_files.entries[i], strlen(test_files.entries[i]), "");
            cgtest_runner_set_error(&result, msg);
            goto cleanup;
        }
        file_contents_count++;

        functions = ctestscanner_find(file_contents[i], file_lengths[i], &count);

        if (count > 0) {
            runner_files[runner_file_count].label = test_files.entries[i];
            runner_files[runner_file_count].functions = functions;
            runner_files[runner_file_count].function_count = count;
            runner_file_count++;
        }
    }

    if (runner_file_count == 0) {
        cgtest_runner_set_error(&result, "no test_ functions found in any test_*.c file");
        goto cleanup;
    }

    if (!cgtest_runner_check_fixtures(runner_files, runner_file_count, file_contents, file_lengths,
                                       test_files.count, &result)) {
        goto cleanup;
    }

    /* Every discovered file is passed to the compiler as its own
     * source argument (see cgtest_runner_build_compile_command()), not
     * resolved via an include search anymore - but two test files
     * sharing a basename across different test_directories is still
     * rejected outright: MSVC's cl.exe names each source file's object
     * file after its own basename by default, so two same-named files
     * from different directories in one compile invocation would
     * silently collide (whichever compiles second overwrites the
     * first's object file). Reject that up front rather than risk a
     * silently-wrong build. */
    for (i = 0; i < runner_file_count; i++) {
        size_t k;
        for (k = i + 1; k < runner_file_count; k++) {
            const char *name_i = cgtest_runner_basename(runner_files[i].label);
            const char *name_k = cgtest_runner_basename(runner_files[k].label);
            if (strcmp(name_i, name_k) == 0) {
                char msg[CGTEST_RUNNER_ERROR_BUFSZ];
                cmsg_build(msg, sizeof(msg), "duplicate test file name across test_directories: ", name_i, strlen(name_i), "");
                cgtest_runner_set_error(&result, msg);
                goto cleanup;
            }
        }
    }

    /* "scan" ends here: discovery, function scanning, and every
     * pre-compile validation check above are done - everything below
     * is building/writing cgtest-runner.c itself. */
    t_now = ctimer_now_ms();
    scan_ms = t_now - t_phase;
    t_phase = t_now;

    if (stat(project->output_path, &st) != 0) {
        if (CGTEST_RUNNER_MKDIR(project->output_path) != 0) {
            char msg[CGTEST_RUNNER_ERROR_BUFSZ];
            cmsg_build(msg, sizeof(msg), "could not create output directory ", project->output_path, strlen(project->output_path), "");
            cgtest_runner_set_error(&result, msg);
            goto cleanup;
        }
    } else if (!S_ISDIR(st.st_mode)) {
        char msg[CGTEST_RUNNER_ERROR_BUFSZ];
        cmsg_build(msg, sizeof(msg), "not a directory: ", project->output_path, strlen(project->output_path), "");
        cgtest_runner_set_error(&result, msg);
        goto cleanup;
    }

    runner_c_path = cpath_join(runner_c_scratch, sizeof(runner_c_scratch), project->output_path, "cgtest-runner.c");
    runner_bin_path = cpath_join(runner_bin_scratch, sizeof(runner_bin_scratch), project->output_path,
                                  "cgtest-runner" CGTEST_RUNNER_EXE_SUFFIX);

    /* Computed before generate_source() (rather than alongside the
     * system() call below) so its text can be embedded as a leading
     * comment in cgtest-runner.c itself - handy for anyone who wants
     * to see or re-run the exact compile invocation without digging
     * through cgtest.exe's own output. */
    compile_cmd = cgtest_runner_build_compile_command(project, runner_files, runner_file_count, runner_c_path.data, runner_bin_path.data);
    if (compile_cmd == NULL) {
        cgtest_runner_set_error(&result, "out of memory");
        goto cleanup;
    }

    source = cgtest_runner_generate_source(runner_files, runner_file_count, compile_cmd);
    if (source == NULL) {
        cgtest_runner_set_error(&result, "out of memory");
        goto cleanup;
    }

    f = fopen(runner_c_path.data, "wb");
    if (f == NULL) {
        char msg[CGTEST_RUNNER_ERROR_BUFSZ];
        cmsg_build(msg, sizeof(msg), "could not create ", runner_c_path.data, runner_c_path.length, "");
        cgtest_runner_set_error(&result, msg);
        goto cleanup;
    }
    {
        size_t len = strlen(source);
        if (fwrite(source, 1, len, f) != len) {
            fclose(f);
            cgtest_runner_set_error(&result, "could not write cgtest-runner.c");
            goto cleanup;
        }
    }
    fclose(f);

    t_now = ctimer_now_ms();
    generate_ms = t_now - t_phase;
    t_phase = t_now;

    system_result = system(compile_cmd);

    /* Measured immediately after the call, before checking whether it
     * failed - compile_ms reflects time actually spent compiling
     * either way, useful even (especially) when the compile fails. */
    t_now = ctimer_now_ms();
    compile_ms = t_now - t_phase;
    t_phase = t_now;

    if (system_result != 0) {
        cgtest_runner_set_error(&result, "compilation failed (see compiler output above)");
        goto cleanup;
    }

    {
        char exec_cmd[CGTEST_RUNNER_PATH_SCRATCH + 4];
        cmsg_build(exec_cmd, sizeof(exec_cmd), "\"", runner_bin_path.data, runner_bin_path.length, "\"");
        system_result = system(exec_cmd);
    }

    /* Same reasoning as compile_ms above - measured before the
     * system_result == -1 check. */
    t_now = ctimer_now_ms();
    run_ms = t_now - t_phase;

    if (system_result == -1) {
        cgtest_runner_set_error(&result, "could not execute cgtest-runner");
        goto cleanup;
    }

    result.ok = 1;
    result.error = NULL;
    result.exit_code = cgtest_runner_decode_exit(system_result);

cleanup:
    result.scan_ms = scan_ms;
    result.generate_ms = generate_ms;
    result.compile_ms = compile_ms;
    result.run_ms = run_ms;
    result.total_ms = ctimer_now_ms() - t_start;

    free(compile_cmd);
    free(source);
    for (i = 0; i < runner_file_count; i++) {
        ctestscanner_free(runner_files[i].functions, runner_files[i].function_count);
    }
    free(runner_files);
    for (i = 0; i < file_contents_count; i++) {
        free(file_contents[i]);
    }
    free(file_contents);
    free(file_lengths);
    cpathlist_free(&test_files);
    return result;
}

void cgtest_runner_free(CGTestRunResult *result)
{
    free(result->error);
    result->error = NULL;
}
