/* cgtest_runner.c - see cgtest_runner.h.
 *
 * cgtest_runner_generate_source() is pure string-building (see
 * CGTestRunnerBuf below, a small growable buffer local to this file -
 * unlike cmsg.h's fixed-size messages, a generated C source file or a
 * compiler command line has no reasonable upper bound, so this one
 * grows). cgtest_runner_run() is everything around it: discovering
 * test files/functions, writing the generated source to disk, and
 * shelling out to the compiler and the resulting binary via system() -
 * acceptable here since compiler_command comes from the user's own
 * trusted cgtest-config.json, the same trust boundary cgtest already
 * crosses by running that compiler at all.
 */
#include "cgtest_runner.h"
#include "ctestfiles.h"
#include "cpath.h"
#include "cmsg.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#ifdef _WIN32
#include <direct.h>
#define CGTEST_RUNNER_MKDIR(path) _mkdir(path)
#define CGTEST_RUNNER_EXE_SUFFIX  ".exe"
static int cgtest_runner_decode_exit(int system_result)
{
    return system_result;
}
#else
#include <unistd.h>
#include <sys/wait.h>
#define CGTEST_RUNNER_MKDIR(path) mkdir(path, 0755)
#define CGTEST_RUNNER_EXE_SUFFIX  ""
static int cgtest_runner_decode_exit(int system_result)
{
    if (system_result == -1) {
        return -1;
    }
    if (WIFEXITED(system_result)) {
        return WEXITSTATUS(system_result);
    }
    return 1;
}
#endif

#define CGTEST_RUNNER_PATH_SCRATCH 4096
#define CGTEST_RUNNER_ERROR_BUFSZ  256

/* A small growable buffer for building unbounded-length text (a
 * generated C source file, or a compiler command line with an
 * arbitrary number of paths) - grows by doubling, like ctestscanner's
 * CTestFunctionList. */
typedef struct {
    char   *data;
    size_t  length;
    size_t  capacity;
} CGTestRunnerBuf;

static int cgtest_runner_buf_init(CGTestRunnerBuf *buf)
{
    buf->capacity = 256;
    buf->length = 0;
    buf->data = (char *)malloc(buf->capacity);
    if (buf->data == NULL) {
        return 0;
    }
    buf->data[0] = '\0';
    return 1;
}

static int cgtest_runner_buf_append(CGTestRunnerBuf *buf, const char *text, size_t text_len)
{
    if (buf->length + text_len + 1 > buf->capacity) {
        size_t new_capacity = buf->capacity;
        char *grown;
        while (new_capacity < buf->length + text_len + 1) {
            new_capacity *= 2;
        }
        grown = (char *)realloc(buf->data, new_capacity);
        if (grown == NULL) {
            return 0;
        }
        buf->data = grown;
        buf->capacity = new_capacity;
    }
    memcpy(buf->data + buf->length, text, text_len);
    buf->length += text_len;
    buf->data[buf->length] = '\0';
    return 1;
}

static int cgtest_runner_buf_append_cstr(CGTestRunnerBuf *buf, const char *text)
{
    return cgtest_runner_buf_append(buf, text, strlen(text));
}

/* Returns a pointer to the filename portion of "path" (everything
 * after its last '/'). Every path this module deals with was built
 * via cpath_join()/cpathlist_register(), which always normalizes to
 * '/' regardless of platform (see cpath.h), so a plain '/' search is
 * enough here - no separate '\\' case is needed. */
static const char *cgtest_runner_basename(const char *path)
{
    const char *slash = strrchr(path, '/');
    return slash != NULL ? slash + 1 : path;
}

char *cgtest_runner_generate_source(const CGTestRunnerFile *files, size_t file_count, const char *compile_command)
{
    CGTestRunnerBuf buf;
    size_t i;
    size_t j;

    if (!cgtest_runner_buf_init(&buf)) {
        return NULL;
    }

    if (!cgtest_runner_buf_append_cstr(&buf, "/* Generated by cgtest.exe - do not edit. */\n") ||
        !cgtest_runner_buf_append_cstr(&buf, "/* compile: ") ||
        !cgtest_runner_buf_append_cstr(&buf, compile_command) ||
        !cgtest_runner_buf_append_cstr(&buf, " */\n") ||
        !cgtest_runner_buf_append_cstr(&buf,
            "#include <stdio.h>\n"
            /* isatty() is POSIX, not ISO C, so it needs its own header
             * per platform - used below to decide whether the
             * [ RUN ]/[ OK ]/[ FAILED ] lines get ANSI color codes.
             * Same reasoning as GoogleTest's own color detection: color
             * codes are only meaningful on a real terminal, and would
             * otherwise pollute output piped into a log file or an
             * editor's quickfix list. */
            "#ifdef _WIN32\n"
            "#include <io.h>\n"
            "#define CGTEST_ISATTY(fd) _isatty(fd)\n"
            "#else\n"
            "#include <unistd.h>\n"
            "#define CGTEST_ISATTY(fd) isatty(fd)\n"
            "#endif\n"
            "\n"
            "int cgtest_failed = 0;\n"
            "\n")) {
        goto fail;
    }

    for (i = 0; i < file_count; i++) {
        if (!cgtest_runner_buf_append_cstr(&buf, "#include \"") ||
            !cgtest_runner_buf_append_cstr(&buf, cgtest_runner_basename(files[i].label)) ||
            !cgtest_runner_buf_append_cstr(&buf, "\"\n")) {
            goto fail;
        }
    }

    if (!cgtest_runner_buf_append_cstr(&buf,
            "\n"
            "int main(void)\n"
            "{\n"
            "    int total = 0;\n"
            "    int failed = 0;\n"
            "    int file_total = 0;\n"
            "    int file_failed = 0;\n"
            "    const char *cgtest_green;\n"
            "    const char *cgtest_red;\n"
            "    const char *cgtest_reset;\n"
            "\n"
            /* Without this, stdout is fully block-buffered whenever it
             * isn't a tty (piped, redirected, or captured by an
             * editor's :make) - every printf() below would then sit
             * buffered until exit while stderr's FAIL: lines (from
             * EXPECT_TRUE/EXPECT_FALSE/ASSERT_TRUE/ASSERT_FALSE)
             * appear immediately, making failures print out of
             * chronological order. */
            "    setvbuf(stdout, NULL, _IOLBF, 0);\n"
            "    cgtest_green = CGTEST_ISATTY(1) ? \"\\x1b[32m\" : \"\";\n"
            "    cgtest_red   = CGTEST_ISATTY(1) ? \"\\x1b[31m\" : \"\";\n"
            "    cgtest_reset = CGTEST_ISATTY(1) ? \"\\x1b[0m\"  : \"\";\n"
            "\n")) {
        goto fail;
    }

    for (i = 0; i < file_count; i++) {
        if (files[i].function_count == 0) {
            continue;
        }

        if (!cgtest_runner_buf_append_cstr(&buf, "    file_total = 0;\n    file_failed = 0;\n") ||
            !cgtest_runner_buf_append_cstr(&buf, "    printf(\"== ") ||
            !cgtest_runner_buf_append_cstr(&buf, cgtest_runner_basename(files[i].label)) ||
            !cgtest_runner_buf_append_cstr(&buf, " ==\\n\");\n")) {
            goto fail;
        }

        for (j = 0; j < files[i].function_count; j++) {
            const char *name = files[i].functions[j].name;
            /* Printed before the call, not after: whether the test
             * passed isn't known until it's actually run, so this
             * announces which test any FAIL: lines below belong to -
             * same reason GoogleTest has "[ RUN      ]" ahead of its
             * "[       OK ]"/"[  FAILED  ]" verdict rather than trying
             * to print the verdict first. Bracket text/width matches
             * GoogleTest's own literally, not just the general idea. */
            /* Color wraps only the bracket token itself, matching
             * GoogleTest exactly: its PrettyUnitTestResultPrinter
             * colors "[ RUN      ]"/"[       OK ]"/"[  FAILED  ]" but
             * prints the test name after it in the default color. */
            if (!cgtest_runner_buf_append_cstr(&buf, "    printf(\"%s[ RUN      ]%s ") ||
                !cgtest_runner_buf_append_cstr(&buf, name) ||
                !cgtest_runner_buf_append_cstr(&buf, "\\n\", cgtest_green, cgtest_reset);\n    total++;\n    file_total++;\n    cgtest_failed = 0;\n    ") ||
                !cgtest_runner_buf_append_cstr(&buf, name) ||
                !cgtest_runner_buf_append_cstr(&buf, "();\n    if (!cgtest_failed) {\n        printf(\"%s[       OK ]%s ") ||
                !cgtest_runner_buf_append_cstr(&buf, name) ||
                !cgtest_runner_buf_append_cstr(&buf, "\\n\", cgtest_green, cgtest_reset);\n    } else {\n        printf(\"%s[  FAILED  ]%s ") ||
                !cgtest_runner_buf_append_cstr(&buf, name) ||
                !cgtest_runner_buf_append_cstr(&buf, "\\n\", cgtest_red, cgtest_reset);\n        failed++;\n        file_failed++;\n    }\n")) {
                goto fail;
            }
        }

        if (!cgtest_runner_buf_append_cstr(&buf,
                "    printf(\"\\n%s%d/%d passed%s\\n\\n\", file_failed == 0 ? cgtest_green : cgtest_red, "
                "file_total - file_failed, file_total, cgtest_reset);\n\n")) {
            goto fail;
        }
    }

    if (!cgtest_runner_buf_append_cstr(&buf,
            "    printf(\"%stotal %d/%d tests passed%s\\n\", failed == 0 ? cgtest_green : cgtest_red, "
            "total - failed, total, cgtest_reset);\n"
            "    return failed == 0 ? 0 : 1;\n"
            "}\n")) {
        goto fail;
    }

    return buf.data;

fail:
    free(buf.data);
    return NULL;
}

static void cgtest_runner_set_error(CGTestRunResult *result, const char *message)
{
    result->ok = 0;
    result->error = cmsg_dup(message, strlen(message));
}

/* Reads "path" whole into a malloc'd, NUL-terminated buffer, setting
 * *out_length to the byte count read (excluding the NUL). Returns
 * NULL on any I/O or allocation failure. */
static char *cgtest_runner_read_file(const char *path, size_t *out_length)
{
    FILE *f;
    long size;
    char *buffer;
    size_t read_count;

    f = fopen(path, "rb");
    if (f == NULL) {
        return NULL;
    }

    if (fseek(f, 0, SEEK_END) != 0 || (size = ftell(f)) < 0 || fseek(f, 0, SEEK_SET) != 0) {
        fclose(f);
        return NULL;
    }

    buffer = (char *)malloc((size_t)size + 1);
    if (buffer == NULL) {
        fclose(f);
        return NULL;
    }

    read_count = fread(buffer, 1, (size_t)size, f);
    fclose(f);
    if (read_count != (size_t)size) {
        free(buffer);
        return NULL;
    }
    buffer[size] = '\0';

    *out_length = (size_t)size;
    return buffer;
}

/* Note: discovered test_*.c files are deliberately NOT passed here as
 * separate compilation units - cgtest-runner.c already pulls each one
 * in via its own #include "<basename>" line (see
 * cgtest_runner_generate_source()), so compiling them again here would
 * duplicate every test_ function's definition and fail to link.
 * Instead, every test_directories entry is added as its own -I so the
 * compiler's quoted-include search finds each bare filename - safe
 * because cgtest_runner_run() has already rejected any basename that
 * appears in more than one test_directories entry. */
static char *cgtest_runner_build_compile_command(const CGTestConfig *config,
                                                  const char *runner_c_path, const char *runner_bin_path)
{
    CGTestRunnerBuf buf;
    size_t i;

    if (!cgtest_runner_buf_init(&buf)) {
        return NULL;
    }

    if (!cgtest_runner_buf_append_cstr(&buf, config->compiler_command)) {
        goto fail;
    }

    for (i = 0; i < config->include_paths.count; i++) {
        if (!cgtest_runner_buf_append_cstr(&buf, " -I\"") ||
            !cgtest_runner_buf_append_cstr(&buf, config->include_paths.entries[i]) ||
            !cgtest_runner_buf_append_cstr(&buf, "\"")) {
            goto fail;
        }
    }
    for (i = 0; i < config->test_directories.count; i++) {
        if (!cgtest_runner_buf_append_cstr(&buf, " -I\"") ||
            !cgtest_runner_buf_append_cstr(&buf, config->test_directories.entries[i]) ||
            !cgtest_runner_buf_append_cstr(&buf, "\"")) {
            goto fail;
        }
    }
    for (i = 0; i < config->source_files.count; i++) {
        if (!cgtest_runner_buf_append_cstr(&buf, " \"") ||
            !cgtest_runner_buf_append_cstr(&buf, config->source_files.entries[i]) ||
            !cgtest_runner_buf_append_cstr(&buf, "\"")) {
            goto fail;
        }
    }
    if (!cgtest_runner_buf_append_cstr(&buf, " \"") ||
        !cgtest_runner_buf_append_cstr(&buf, runner_c_path) ||
        !cgtest_runner_buf_append_cstr(&buf, "\" -o \"") ||
        !cgtest_runner_buf_append_cstr(&buf, runner_bin_path) ||
        !cgtest_runner_buf_append_cstr(&buf, "\"")) {
        goto fail;
    }

    return buf.data;

fail:
    free(buf.data);
    return NULL;
}

CGTestRunResult cgtest_runner_run(const CGTestConfig *config)
{
    CGTestRunResult result;
    CPathList test_files;
    CGTestRunnerFile *runner_files;
    size_t runner_file_count;
    char *source;
    char runner_c_scratch[CGTEST_RUNNER_PATH_SCRATCH];
    char runner_bin_scratch[CGTEST_RUNNER_PATH_SCRATCH];
    CPath runner_c_path;
    CPath runner_bin_path;
    struct stat st;
    FILE *f;
    char *compile_cmd;
    int system_result;
    size_t i;

    result.ok = 0;
    result.error = NULL;
    result.exit_code = -1;

    cpathlist_init(&test_files);
    runner_files = NULL;
    runner_file_count = 0;
    source = NULL;
    compile_cmd = NULL;

    for (i = 0; i < config->test_directories.count; i++) {
        CTestFileScan scan = ctestfiles_scan(config->test_directories.entries[i]);
        size_t j;

        if (!scan.ok) {
            cgtest_runner_set_error(&result, scan.error);
            ctestfiles_free(&scan);
            goto cleanup;
        }

        for (j = 0; j < scan.files.count; j++) {
            if (cpathlist_register(&test_files, "", scan.files.entries[j]) == CPATHLIST_ALLOC_FAILED) {
                cgtest_runner_set_error(&result, "out of memory");
                ctestfiles_free(&scan);
                goto cleanup;
            }
        }
        ctestfiles_free(&scan);
    }

    if (test_files.count == 0) {
        cgtest_runner_set_error(&result, "no test_*.c files found in any test_directories entry");
        goto cleanup;
    }

    runner_files = (CGTestRunnerFile *)malloc(test_files.count * sizeof(CGTestRunnerFile));
    if (runner_files == NULL) {
        cgtest_runner_set_error(&result, "out of memory");
        goto cleanup;
    }

    for (i = 0; i < test_files.count; i++) {
        char *content;
        size_t length;
        CTestFunction *functions;
        size_t count;

        content = cgtest_runner_read_file(test_files.entries[i], &length);
        if (content == NULL) {
            char msg[CGTEST_RUNNER_ERROR_BUFSZ];
            cmsg_build(msg, sizeof(msg), "could not read test file: ", test_files.entries[i], strlen(test_files.entries[i]), "");
            cgtest_runner_set_error(&result, msg);
            goto cleanup;
        }

        functions = ctestscanner_find(content, length, &count);
        free(content);

        if (count > 0) {
            runner_files[runner_file_count].label = test_files.entries[i];
            runner_files[runner_file_count].functions = functions;
            runner_files[runner_file_count].function_count = count;
            runner_file_count++;
        }
    }

    if (runner_file_count == 0) {
        cgtest_runner_set_error(&result, "no test_ functions found in any test_*.c file");
        goto cleanup;
    }

    /* The generated source #includes each file by its bare basename
     * (see cgtest_runner_generate_source()), resolved at compile time
     * via a -I per test_directories entry - so two files sharing a
     * basename across different test_directories would silently
     * resolve to whichever one the compiler's search order finds
     * first. Reject that up front rather than risk compiling the
     * wrong file. */
    for (i = 0; i < runner_file_count; i++) {
        size_t k;
        for (k = i + 1; k < runner_file_count; k++) {
            const char *name_i = cgtest_runner_basename(runner_files[i].label);
            const char *name_k = cgtest_runner_basename(runner_files[k].label);
            if (strcmp(name_i, name_k) == 0) {
                char msg[CGTEST_RUNNER_ERROR_BUFSZ];
                cmsg_build(msg, sizeof(msg), "duplicate test file name across test_directories: ", name_i, strlen(name_i), "");
                cgtest_runner_set_error(&result, msg);
                goto cleanup;
            }
        }
    }

    if (stat(config->output_path, &st) != 0) {
        if (CGTEST_RUNNER_MKDIR(config->output_path) != 0) {
            char msg[CGTEST_RUNNER_ERROR_BUFSZ];
            cmsg_build(msg, sizeof(msg), "could not create output directory ", config->output_path, strlen(config->output_path), "");
            cgtest_runner_set_error(&result, msg);
            goto cleanup;
        }
    } else if (!S_ISDIR(st.st_mode)) {
        char msg[CGTEST_RUNNER_ERROR_BUFSZ];
        cmsg_build(msg, sizeof(msg), "not a directory: ", config->output_path, strlen(config->output_path), "");
        cgtest_runner_set_error(&result, msg);
        goto cleanup;
    }

    runner_c_path = cpath_join(runner_c_scratch, sizeof(runner_c_scratch), config->output_path, "cgtest-runner.c");
    runner_bin_path = cpath_join(runner_bin_scratch, sizeof(runner_bin_scratch), config->output_path,
                                  "cgtest-runner" CGTEST_RUNNER_EXE_SUFFIX);

    /* Computed before generate_source() (rather than alongside the
     * system() call below) so its text can be embedded as a leading
     * comment in cgtest-runner.c itself - handy for anyone who wants
     * to see or re-run the exact compile invocation without digging
     * through cgtest.exe's own output. */
    compile_cmd = cgtest_runner_build_compile_command(config, runner_c_path.data, runner_bin_path.data);
    if (compile_cmd == NULL) {
        cgtest_runner_set_error(&result, "out of memory");
        goto cleanup;
    }

    source = cgtest_runner_generate_source(runner_files, runner_file_count, compile_cmd);
    if (source == NULL) {
        cgtest_runner_set_error(&result, "out of memory");
        goto cleanup;
    }

    f = fopen(runner_c_path.data, "wb");
    if (f == NULL) {
        char msg[CGTEST_RUNNER_ERROR_BUFSZ];
        cmsg_build(msg, sizeof(msg), "could not create ", runner_c_path.data, runner_c_path.length, "");
        cgtest_runner_set_error(&result, msg);
        goto cleanup;
    }
    {
        size_t len = strlen(source);
        if (fwrite(source, 1, len, f) != len) {
            fclose(f);
            cgtest_runner_set_error(&result, "could not write cgtest-runner.c");
            goto cleanup;
        }
    }
    fclose(f);

    system_result = system(compile_cmd);
    if (system_result != 0) {
        cgtest_runner_set_error(&result, "compilation failed (see compiler output above)");
        goto cleanup;
    }

    {
        char exec_cmd[CGTEST_RUNNER_PATH_SCRATCH + 4];
        cmsg_build(exec_cmd, sizeof(exec_cmd), "\"", runner_bin_path.data, runner_bin_path.length, "\"");
        system_result = system(exec_cmd);
    }
    if (system_result == -1) {
        cgtest_runner_set_error(&result, "could not execute cgtest-runner");
        goto cleanup;
    }

    result.ok = 1;
    result.error = NULL;
    result.exit_code = cgtest_runner_decode_exit(system_result);

cleanup:
    free(compile_cmd);
    free(source);
    for (i = 0; i < runner_file_count; i++) {
        ctestscanner_free(runner_files[i].functions, runner_files[i].function_count);
    }
    free(runner_files);
    cpathlist_free(&test_files);
    return result;
}

void cgtest_runner_free(CGTestRunResult *result)
{
    free(result->error);
    result->error = NULL;
}
