#ifndef CGTEST_H
#define CGTEST_H

/* Generated by "cgtest --create". Test functions have the form
 * "void test_<name>(void) { ... }" - a plain "void" keeps test
 * files C89-portable (no <stdbool.h>). EXPECT_* macros report a
 * failed check and keep running the test; ASSERT_* macros report
 * it and return immediately - use ASSERT for a precondition the
 * rest of the function depends on (e.g. a NULL check before a
 * dereference), EXPECT otherwise.
 * The EXPECT_EQ_INT/UINT/DOUBLE/PTR/STR/STR_NOCASE macros (and their
 * ASSERT_EQ_ counterparts) additionally print both operands'
 * values on failure. */

#include <ctype.h>
#include <stdio.h>
#include <string.h>

#ifdef _WIN32
#include <direct.h>
#define CGTEST_GETCWD _getcwd
#else
#include <unistd.h>
#define CGTEST_GETCWD getcwd
#endif

/* The generated runner reads this after calling each test to
 * decide pass/fail, resetting it to 0 first. */
extern int cgtest_failed;

/* Shortens __FILE__ to a path relative to the current working
 * directory (falls back to the full path if it isn't under it),
 * so FAIL messages stay short - jump-to-file in an editor's
 * quickfix list still works as long as the editor's own cwd
 * matches wherever the test binary was run from. */
static const char *cgtest_relpath(const char *file)
{
    static char cwd[4096];
    size_t i;
    size_t len;

    if (CGTEST_GETCWD(cwd, sizeof(cwd)) == NULL) {
        return file;
    }

    len = strlen(cwd);
    for (i = 0; i < len; i++) {
        char a = file[i];
        char b = cwd[i];
        if (a == '\\') a = '/';
        if (b == '\\') b = '/';
        if (a != b) {
            return file;
        }
    }
    if (file[len] != '/' && file[len] != '\\') {
        return file;
    }
    return file + len + 1;
}

static void cgtest_print_str_field(const char *prefix, const char *s)
{
    size_t indent = strlen(prefix);
    int first = 1;
    size_t i;
    unsigned char c;

    for (;;) {
        if (first) {
            fprintf(stderr, "%s\"", prefix);
            first = 0;
        } else {
            for (i = 0; i < indent; i++) {
                fputc(' ', stderr);
            }
            fputc('"', stderr);
        }

        for (;;) {
            c = (unsigned char)*s;
            if (c == '\0') {
                fputs("\"\n", stderr);
                return;
            }
            if (c == '\n') {
                fputs("\\n\"\n", stderr);
                s++;
                break;
            }
            switch (c) {
                case '\r': fputs("\\r", stderr); break;
                case '\t': fputs("\\t", stderr); break;
                case '\a': fputs("\\a", stderr); break;
                case '\b': fputs("\\b", stderr); break;
                case '\v': fputs("\\v", stderr); break;
                case '\f': fputs("\\f", stderr); break;
                default:
                    if (c < 0x20 || c >= 0x7f) {
                        fprintf(stderr, "\\x%02x", (unsigned int)c);
                    } else {
                        fputc((int)c, stderr);
                    }
                    break;
            }
            s++;
        }
    }
}

#define EXPECT_TRUE(cond) \
    do { \
        if (!(cond)) { \
            fprintf(stderr, "%s:%d: FAIL: EXPECT_TRUE(%s)\n", cgtest_relpath(__FILE__), __LINE__, #cond); \
            cgtest_failed = 1; \
        } \
    } while (0)

#define EXPECT_FALSE(cond) \
    do { \
        if (cond) { \
            fprintf(stderr, "%s:%d: FAIL: EXPECT_FALSE(%s)\n", cgtest_relpath(__FILE__), __LINE__, #cond); \
            cgtest_failed = 1; \
        } \
    } while (0)

#define ASSERT_TRUE(cond) \
    do { \
        if (!(cond)) { \
            fprintf(stderr, "%s:%d: FAIL: ASSERT_TRUE(%s)\n", cgtest_relpath(__FILE__), __LINE__, #cond); \
            cgtest_failed = 1; \
            return; \
        } \
    } while (0)

#define ASSERT_FALSE(cond) \
    do { \
        if (cond) { \
            fprintf(stderr, "%s:%d: FAIL: ASSERT_FALSE(%s)\n", cgtest_relpath(__FILE__), __LINE__, #cond); \
            cgtest_failed = 1; \
            return; \
        } \
    } while (0)

#define EXPECT_EQ_INT(expected, actual) \
    do { \
        long cgtest_exp_ = (long)(expected); \
        long cgtest_act_ = (long)(actual); \
        if (cgtest_exp_ != cgtest_act_) { \
            fprintf(stderr, "%s:%d: FAIL: EXPECT_EQ_INT(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \
            fprintf(stderr, "  expected: %ld\n  actual:   %ld\n", cgtest_exp_, cgtest_act_); \
            cgtest_failed = 1; \
        } \
    } while (0)

#define ASSERT_EQ_INT(expected, actual) \
    do { \
        long cgtest_exp_ = (long)(expected); \
        long cgtest_act_ = (long)(actual); \
        if (cgtest_exp_ != cgtest_act_) { \
            fprintf(stderr, "%s:%d: FAIL: ASSERT_EQ_INT(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \
            fprintf(stderr, "  expected: %ld\n  actual:   %ld\n", cgtest_exp_, cgtest_act_); \
            cgtest_failed = 1; \
            return; \
        } \
    } while (0)

#define EXPECT_EQ_UINT(expected, actual) \
    do { \
        unsigned long cgtest_exp_ = (unsigned long)(expected); \
        unsigned long cgtest_act_ = (unsigned long)(actual); \
        if (cgtest_exp_ != cgtest_act_) { \
            fprintf(stderr, "%s:%d: FAIL: EXPECT_EQ_UINT(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \
            fprintf(stderr, "  expected: %lu\n  actual:   %lu\n", cgtest_exp_, cgtest_act_); \
            cgtest_failed = 1; \
        } \
    } while (0)

#define ASSERT_EQ_UINT(expected, actual) \
    do { \
        unsigned long cgtest_exp_ = (unsigned long)(expected); \
        unsigned long cgtest_act_ = (unsigned long)(actual); \
        if (cgtest_exp_ != cgtest_act_) { \
            fprintf(stderr, "%s:%d: FAIL: ASSERT_EQ_UINT(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \
            fprintf(stderr, "  expected: %lu\n  actual:   %lu\n", cgtest_exp_, cgtest_act_); \
            cgtest_failed = 1; \
            return; \
        } \
    } while (0)

#define EXPECT_EQ_DOUBLE(expected, actual) \
    do { \
        double cgtest_exp_ = (double)(expected); \
        double cgtest_act_ = (double)(actual); \
        if (cgtest_exp_ != cgtest_act_) { \
            fprintf(stderr, "%s:%d: FAIL: EXPECT_EQ_DOUBLE(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \
            fprintf(stderr, "  expected: %g\n  actual:   %g\n", cgtest_exp_, cgtest_act_); \
            cgtest_failed = 1; \
        } \
    } while (0)

#define ASSERT_EQ_DOUBLE(expected, actual) \
    do { \
        double cgtest_exp_ = (double)(expected); \
        double cgtest_act_ = (double)(actual); \
        if (cgtest_exp_ != cgtest_act_) { \
            fprintf(stderr, "%s:%d: FAIL: ASSERT_EQ_DOUBLE(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \
            fprintf(stderr, "  expected: %g\n  actual:   %g\n", cgtest_exp_, cgtest_act_); \
            cgtest_failed = 1; \
            return; \
        } \
    } while (0)

#define EXPECT_EQ_PTR(expected, actual) \
    do { \
        const void *cgtest_exp_ = (const void *)(expected); \
        const void *cgtest_act_ = (const void *)(actual); \
        if (cgtest_exp_ != cgtest_act_) { \
            fprintf(stderr, "%s:%d: FAIL: EXPECT_EQ_PTR(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \
            fprintf(stderr, "  expected: %p\n  actual:   %p\n", cgtest_exp_, cgtest_act_); \
            cgtest_failed = 1; \
        } \
    } while (0)

#define ASSERT_EQ_PTR(expected, actual) \
    do { \
        const void *cgtest_exp_ = (const void *)(expected); \
        const void *cgtest_act_ = (const void *)(actual); \
        if (cgtest_exp_ != cgtest_act_) { \
            fprintf(stderr, "%s:%d: FAIL: ASSERT_EQ_PTR(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \
            fprintf(stderr, "  expected: %p\n  actual:   %p\n", cgtest_exp_, cgtest_act_); \
            cgtest_failed = 1; \
            return; \
        } \
    } while (0)

/* Byte-wise case-insensitive comparison, like strcasecmp() - not
 * used directly since strcasecmp() isn't standard C (POSIX only,
 * and named _stricmp on MSVC); this stays portable to plain
 * C89/C99. Returns 0 on a case-insensitive match, same
 * convention as strcmp(). */
static int cgtest_strcasecmp(const char *a, const char *b)
{
    unsigned char ca, cb;

    for (;;) {
        ca = (unsigned char)*a;
        cb = (unsigned char)*b;
        if (tolower(ca) != tolower(cb)) {
            return 1;
        }
        if (ca == '\0') {
            return 0;
        }
        a++;
        b++;
    }
}

#define EXPECT_EQ_STR(expected, actual) \
    do { \
        const char *cgtest_exp_ = (expected); \
        const char *cgtest_act_ = (actual); \
        if (strcmp(cgtest_exp_, cgtest_act_) != 0) { \
            fprintf(stderr, "%s:%d: FAIL: EXPECT_EQ_STR(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \
            cgtest_print_str_field("  expected: ", cgtest_exp_); \
            cgtest_print_str_field("  actual:   ", cgtest_act_); \
            cgtest_failed = 1; \
        } \
    } while (0)

#define ASSERT_EQ_STR(expected, actual) \
    do { \
        const char *cgtest_exp_ = (expected); \
        const char *cgtest_act_ = (actual); \
        if (strcmp(cgtest_exp_, cgtest_act_) != 0) { \
            fprintf(stderr, "%s:%d: FAIL: ASSERT_EQ_STR(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \
            cgtest_print_str_field("  expected: ", cgtest_exp_); \
            cgtest_print_str_field("  actual:   ", cgtest_act_); \
            cgtest_failed = 1; \
            return; \
        } \
    } while (0)

#define EXPECT_EQ_STR_NOCASE(expected, actual) \
    do { \
        const char *cgtest_exp_ = (expected); \
        const char *cgtest_act_ = (actual); \
        if (cgtest_strcasecmp(cgtest_exp_, cgtest_act_) != 0) { \
            fprintf(stderr, "%s:%d: FAIL: EXPECT_EQ_STR_NOCASE(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \
            cgtest_print_str_field("  expected: ", cgtest_exp_); \
            cgtest_print_str_field("  actual:   ", cgtest_act_); \
            cgtest_failed = 1; \
        } \
    } while (0)

#define ASSERT_EQ_STR_NOCASE(expected, actual) \
    do { \
        const char *cgtest_exp_ = (expected); \
        const char *cgtest_act_ = (actual); \
        if (cgtest_strcasecmp(cgtest_exp_, cgtest_act_) != 0) { \
            fprintf(stderr, "%s:%d: FAIL: ASSERT_EQ_STR_NOCASE(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #expected, #actual); \
            cgtest_print_str_field("  expected: ", cgtest_exp_); \
            cgtest_print_str_field("  actual:   ", cgtest_act_); \
            cgtest_failed = 1; \
            return; \
        } \
    } while (0)

#endif /* CGTEST_H */
