#ifndef CGTEST_H
#define CGTEST_H

/* Generated by "cgtest --create". Test functions have the form
 * "void test_<name>(void) { ... }"; CGTEST_CHECK() reports a failed
 * assertion and returns from the current test function. The
 * generated runner reads cgtest_failed after calling each test to
 * decide pass/fail, resetting it to 0 first - a plain "void"
 * signature keeps test files C89-portable (no <stdbool.h>). */

#include <stdio.h>

extern int cgtest_failed;

#define CGTEST_CHECK(cond) \
    do { \
        if (!(cond)) { \
            fprintf(stderr, "  FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
            cgtest_failed = 1; \
            return; \
        } \
    } while (0)

#endif /* CGTEST_H */
