#ifndef CGTEST_H
#define CGTEST_H

/* Generated by "cgtest --create". Test functions have the form
 * "void test_<name>(void) { ... }" - a plain "void" keeps test
 * files C89-portable (no <stdbool.h>). EXPECT_* macros report a
 * failed check and keep running the test; ASSERT_* macros report
 * it and return immediately - use ASSERT for a precondition the
 * rest of the function depends on (e.g. a NULL check before a
 * dereference), EXPECT otherwise.
 * The EXPECT_EQ_/EXPECT_NE_ macros (INT/UINT/DOUBLE/PTR/STR/
 * STR_NOCASE, and their ASSERT_ counterparts) additionally print
 * both operands' values on failure. */

#include <ctype.h>
#include <stdio.h>
#include <string.h>

#ifdef _WIN32
#include <direct.h>
#define CGTEST_GETCWD _getcwd
#else
#include <unistd.h>
#define CGTEST_GETCWD getcwd
#endif

/* The generated runner reads this after calling each test to
 * decide pass/fail, resetting it to 0 first. */
extern int cgtest_failed;

/* Shortens __FILE__ to a path relative to the current working
 * directory (falls back to the full path if it isn't under it),
 * so FAIL messages stay short - jump-to-file in an editor's
 * quickfix list still works as long as the editor's own cwd
 * matches wherever the test binary was run from. */
static const char *cgtest_relpath(const char *file)
{
    static char cwd[4096];
    size_t i;
    size_t len;

    if (CGTEST_GETCWD(cwd, sizeof(cwd)) == NULL) {
        return file;
    }

    len = strlen(cwd);
    for (i = 0; i < len; i++) {
        char a = file[i];
        char b = cwd[i];
        if (a == '\\') a = '/';
        if (b == '\\') b = '/';
        if (a != b) {
            return file;
        }
    }
    if (file[len] != '/' && file[len] != '\\') {
        return file;
    }
    return file + len + 1;
}

static void cgtest_print_str_field(const char *prefix, const char *s)
{
    size_t indent = strlen(prefix);
    int first = 1;
    size_t i;
    unsigned char c;

    for (;;) {
        if (first) {
            fprintf(stderr, "%s\"", prefix);
            first = 0;
        } else {
            for (i = 0; i < indent; i++) {
                fputc(' ', stderr);
            }
            fputc('"', stderr);
        }

        for (;;) {
            c = (unsigned char)*s;
            if (c == '\0') {
                fputs("\"\n", stderr);
                return;
            }
            if (c == '\n') {
                fputs("\\n\"\n", stderr);
                s++;
                break;
            }
            switch (c) {
                case '\r': fputs("\\r", stderr); break;
                case '\t': fputs("\\t", stderr); break;
                case '\a': fputs("\\a", stderr); break;
                case '\b': fputs("\\b", stderr); break;
                case '\v': fputs("\\v", stderr); break;
                case '\f': fputs("\\f", stderr); break;
                default:
                    if (c < 0x20 || c >= 0x7f) {
                        fprintf(stderr, "\\x%02x", (unsigned int)c);
                    } else {
                        fputc((int)c, stderr);
                    }
                    break;
            }
            s++;
        }
    }
}

#define EXPECT_TRUE(cond) \
    do { \
        if (!(cond)) { \
            fprintf(stderr, "%s:%d: FAIL: EXPECT_TRUE(%s)\n", cgtest_relpath(__FILE__), __LINE__, #cond); \
            cgtest_failed = 1; \
        } \
    } while (0)

#define EXPECT_FALSE(cond) \
    do { \
        if (cond) { \
            fprintf(stderr, "%s:%d: FAIL: EXPECT_FALSE(%s)\n", cgtest_relpath(__FILE__), __LINE__, #cond); \
            cgtest_failed = 1; \
        } \
    } while (0)

#define ASSERT_TRUE(cond) \
    do { \
        if (!(cond)) { \
            fprintf(stderr, "%s:%d: FAIL: ASSERT_TRUE(%s)\n", cgtest_relpath(__FILE__), __LINE__, #cond); \
            cgtest_failed = 1; \
            return; \
        } \
    } while (0)

#define ASSERT_FALSE(cond) \
    do { \
        if (cond) { \
            fprintf(stderr, "%s:%d: FAIL: ASSERT_FALSE(%s)\n", cgtest_relpath(__FILE__), __LINE__, #cond); \
            cgtest_failed = 1; \
            return; \
        } \
    } while (0)

#define CGTEST_CMP_INT_(macro_name, fail_op, fmt, on_fail, lhs, rhs) \
    do { \
        long cgtest_lhs_ = (long)(lhs); \
        long cgtest_rhs_ = (long)(rhs); \
        if (cgtest_lhs_ fail_op cgtest_rhs_) { \
            fprintf(stderr, "%s:%d: FAIL: " macro_name "(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #lhs, #rhs); \
            fprintf(stderr, fmt, cgtest_lhs_, cgtest_rhs_); \
            cgtest_failed = 1; \
            on_fail; \
        } \
    } while (0)

#define EXPECT_EQ_INT(expected, actual) \
    CGTEST_CMP_INT_("EXPECT_EQ_INT", !=, "  expected: %ld\n  actual:   %ld\n", ((void)0), expected, actual)

#define ASSERT_EQ_INT(expected, actual) \
    CGTEST_CMP_INT_("ASSERT_EQ_INT", !=, "  expected: %ld\n  actual:   %ld\n", return, expected, actual)

#define EXPECT_NE_INT(unexpected, actual) \
    CGTEST_CMP_INT_("EXPECT_NE_INT", ==, "  unexpected: %ld\n  actual:     %ld\n", ((void)0), unexpected, actual)

#define ASSERT_NE_INT(unexpected, actual) \
    CGTEST_CMP_INT_("ASSERT_NE_INT", ==, "  unexpected: %ld\n  actual:     %ld\n", return, unexpected, actual)

#define CGTEST_CMP_UINT_(macro_name, fail_op, fmt, on_fail, lhs, rhs) \
    do { \
        unsigned long cgtest_lhs_ = (unsigned long)(lhs); \
        unsigned long cgtest_rhs_ = (unsigned long)(rhs); \
        if (cgtest_lhs_ fail_op cgtest_rhs_) { \
            fprintf(stderr, "%s:%d: FAIL: " macro_name "(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #lhs, #rhs); \
            fprintf(stderr, fmt, cgtest_lhs_, cgtest_rhs_); \
            cgtest_failed = 1; \
            on_fail; \
        } \
    } while (0)

#define EXPECT_EQ_UINT(expected, actual) \
    CGTEST_CMP_UINT_("EXPECT_EQ_UINT", !=, "  expected: %lu\n  actual:   %lu\n", ((void)0), expected, actual)

#define ASSERT_EQ_UINT(expected, actual) \
    CGTEST_CMP_UINT_("ASSERT_EQ_UINT", !=, "  expected: %lu\n  actual:   %lu\n", return, expected, actual)

#define EXPECT_NE_UINT(unexpected, actual) \
    CGTEST_CMP_UINT_("EXPECT_NE_UINT", ==, "  unexpected: %lu\n  actual:     %lu\n", ((void)0), unexpected, actual)

#define ASSERT_NE_UINT(unexpected, actual) \
    CGTEST_CMP_UINT_("ASSERT_NE_UINT", ==, "  unexpected: %lu\n  actual:     %lu\n", return, unexpected, actual)

#define CGTEST_CMP_DOUBLE_(macro_name, fail_op, fmt, on_fail, lhs, rhs) \
    do { \
        double cgtest_lhs_ = (double)(lhs); \
        double cgtest_rhs_ = (double)(rhs); \
        if (cgtest_lhs_ fail_op cgtest_rhs_) { \
            fprintf(stderr, "%s:%d: FAIL: " macro_name "(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #lhs, #rhs); \
            fprintf(stderr, fmt, cgtest_lhs_, cgtest_rhs_); \
            cgtest_failed = 1; \
            on_fail; \
        } \
    } while (0)

#define EXPECT_EQ_DOUBLE(expected, actual) \
    CGTEST_CMP_DOUBLE_("EXPECT_EQ_DOUBLE", !=, "  expected: %g\n  actual:   %g\n", ((void)0), expected, actual)

#define ASSERT_EQ_DOUBLE(expected, actual) \
    CGTEST_CMP_DOUBLE_("ASSERT_EQ_DOUBLE", !=, "  expected: %g\n  actual:   %g\n", return, expected, actual)

#define EXPECT_NE_DOUBLE(unexpected, actual) \
    CGTEST_CMP_DOUBLE_("EXPECT_NE_DOUBLE", ==, "  unexpected: %g\n  actual:     %g\n", ((void)0), unexpected, actual)

#define ASSERT_NE_DOUBLE(unexpected, actual) \
    CGTEST_CMP_DOUBLE_("ASSERT_NE_DOUBLE", ==, "  unexpected: %g\n  actual:     %g\n", return, unexpected, actual)

#define CGTEST_CMP_PTR_(macro_name, fail_op, fmt, on_fail, lhs, rhs) \
    do { \
        const void *cgtest_lhs_ = (const void *)(lhs); \
        const void *cgtest_rhs_ = (const void *)(rhs); \
        if (cgtest_lhs_ fail_op cgtest_rhs_) { \
            fprintf(stderr, "%s:%d: FAIL: " macro_name "(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #lhs, #rhs); \
            fprintf(stderr, fmt, cgtest_lhs_, cgtest_rhs_); \
            cgtest_failed = 1; \
            on_fail; \
        } \
    } while (0)

#define EXPECT_EQ_PTR(expected, actual) \
    CGTEST_CMP_PTR_("EXPECT_EQ_PTR", !=, "  expected: %p\n  actual:   %p\n", ((void)0), expected, actual)

#define ASSERT_EQ_PTR(expected, actual) \
    CGTEST_CMP_PTR_("ASSERT_EQ_PTR", !=, "  expected: %p\n  actual:   %p\n", return, expected, actual)

#define EXPECT_NE_PTR(unexpected, actual) \
    CGTEST_CMP_PTR_("EXPECT_NE_PTR", ==, "  unexpected: %p\n  actual:     %p\n", ((void)0), unexpected, actual)

#define ASSERT_NE_PTR(unexpected, actual) \
    CGTEST_CMP_PTR_("ASSERT_NE_PTR", ==, "  unexpected: %p\n  actual:     %p\n", return, unexpected, actual)

/* Byte-wise case-insensitive comparison, like strcasecmp() - not
 * used directly since strcasecmp() isn't standard C (POSIX only,
 * and named _stricmp on MSVC); this stays portable to plain
 * C89/C99. Returns 0 on a case-insensitive match, same
 * convention as strcmp(). */
static int cgtest_strcasecmp(const char *a, const char *b)
{
    unsigned char ca, cb;

    for (;;) {
        ca = (unsigned char)*a;
        cb = (unsigned char)*b;
        if (tolower(ca) != tolower(cb)) {
            return 1;
        }
        if (ca == '\0') {
            return 0;
        }
        a++;
        b++;
    }
}

#define CGTEST_CMP_STR_(macro_name, fail_op, lhs_label, rhs_label, on_fail, lhs, rhs) \
    do { \
        const char *cgtest_lhs_ = (lhs); \
        const char *cgtest_rhs_ = (rhs); \
        if (strcmp(cgtest_lhs_, cgtest_rhs_) fail_op 0) { \
            fprintf(stderr, "%s:%d: FAIL: " macro_name "(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #lhs, #rhs); \
            cgtest_print_str_field(lhs_label, cgtest_lhs_); \
            cgtest_print_str_field(rhs_label, cgtest_rhs_); \
            cgtest_failed = 1; \
            on_fail; \
        } \
    } while (0)

#define EXPECT_EQ_STR(expected, actual) \
    CGTEST_CMP_STR_("EXPECT_EQ_STR", !=, "  expected: ", "  actual:   ", ((void)0), expected, actual)

#define ASSERT_EQ_STR(expected, actual) \
    CGTEST_CMP_STR_("ASSERT_EQ_STR", !=, "  expected: ", "  actual:   ", return, expected, actual)

#define EXPECT_NE_STR(unexpected, actual) \
    CGTEST_CMP_STR_("EXPECT_NE_STR", ==, "  unexpected: ", "  actual:     ", ((void)0), unexpected, actual)

#define ASSERT_NE_STR(unexpected, actual) \
    CGTEST_CMP_STR_("ASSERT_NE_STR", ==, "  unexpected: ", "  actual:     ", return, unexpected, actual)

#define CGTEST_CMP_STR_NOCASE_(macro_name, fail_op, lhs_label, rhs_label, on_fail, lhs, rhs) \
    do { \
        const char *cgtest_lhs_ = (lhs); \
        const char *cgtest_rhs_ = (rhs); \
        if (cgtest_strcasecmp(cgtest_lhs_, cgtest_rhs_) fail_op 0) { \
            fprintf(stderr, "%s:%d: FAIL: " macro_name "(%s, %s)\n", \
                    cgtest_relpath(__FILE__), __LINE__, #lhs, #rhs); \
            cgtest_print_str_field(lhs_label, cgtest_lhs_); \
            cgtest_print_str_field(rhs_label, cgtest_rhs_); \
            cgtest_failed = 1; \
            on_fail; \
        } \
    } while (0)

#define EXPECT_EQ_STR_NOCASE(expected, actual) \
    CGTEST_CMP_STR_NOCASE_("EXPECT_EQ_STR_NOCASE", !=, "  expected: ", "  actual:   ", ((void)0), expected, actual)

#define ASSERT_EQ_STR_NOCASE(expected, actual) \
    CGTEST_CMP_STR_NOCASE_("ASSERT_EQ_STR_NOCASE", !=, "  expected: ", "  actual:   ", return, expected, actual)

#define EXPECT_NE_STR_NOCASE(unexpected, actual) \
    CGTEST_CMP_STR_NOCASE_("EXPECT_NE_STR_NOCASE", ==, "  unexpected: ", "  actual:     ", ((void)0), unexpected, actual)

#define ASSERT_NE_STR_NOCASE(unexpected, actual) \
    CGTEST_CMP_STR_NOCASE_("ASSERT_NE_STR_NOCASE", ==, "  unexpected: ", "  actual:     ", return, unexpected, actual)

#endif /* CGTEST_H */
